'use strict';

// FRAME 2.8.0 chat-first companion.
const FRAME_CHAT_KEY='frameAiChatV270';
const FRAME_CHAT_PENDING_KEY='frameAiPendingV270';
const FRAME_CHAT_TOPIC_KEY='frameAiTopicV270';
const FRAME_CHAT_LIMIT=100;
const FRAME_TEST_TRANSCRIPT_KEY='frameAiTestTranscriptV278';
const FRAME_RETIRED_TEST_TRANSCRIPT_KEYS=['frameAiTestTranscriptV277'];
const FRAME_TEST_TRANSCRIPT_FORMAT='FRAME_TEST_TRANSCRIPT';
const FRAME_TEST_TRANSCRIPT_SCHEMA=1;
const FRAME_TEST_TRANSCRIPT_DAYS=7;
const FRAME_TEST_TEXT_LIMIT=12000;
const FRAME_OWNER_TEST_OUTBOX_KEY='frameOwnerTestOutboxV279';
const FRAME_OWNER_TEST_OUTBOX_LIMIT=1000;
const FRAME_OWNER_TEST_MAX_EVENT_BYTES=60*1024;
const FRAME_OWNER_TEST_MAX_BATCH_BYTES=480*1024;
const FRAME_OWNER_TEST_DESTINATION_LIMIT=32;
const FRAME_OWNER_TEST_RETRY_LIMIT=6;
const FRAME_OWNER_TEST_RETRY_BASE_MS=1000;
const FRAME_OWNER_TEST_RETRY_MAX_MS=30000;
const FRAME_TEST_PAGE_ID=typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;
let frameVoiceWanted=false,frameVoiceStopping=false,frameVoiceStopPromise=null,frameComposerWakeWanted=false,frameVoiceRestartTimer=null,frameComposerWakeTimer=null,frameVoiceBase='',frameVoiceFinal='',frameVoiceInterim='',frameVoiceStartedAt=0,frameVoiceUiTimer=null,frameVoiceWakeLock=null,frameWakeAcquirePromise=null,frameVoiceSession=0,frameThinking=false,frameApplyingDraftId='',frameOwnerFlushTimer=null,frameOwnerFlushBusy=false,frameOwnerRetryAttempt=0,frameOwnerVerifiedCredential='',frameMutationClarificationSession='';
let frameVoiceEndWaiter=null;
const frameSessionMessageIds=new Set();
let frameChatSession=[],framePendingSession=null,frameTopicSession='',frameComposerDraftSession='';

function frameRetireLegacyAiChatStorage(){for(const key of [FRAME_CHAT_KEY,FRAME_CHAT_PENDING_KEY,FRAME_CHAT_TOPIC_KEY,...FRAME_RETIRED_TEST_TRANSCRIPT_KEYS]){try{if(typeof storageRemove==='function')storageRemove(key);else localStorage.removeItem(key)}catch(e){}}}
frameRetireLegacyAiChatStorage();
function frameTestString(value,limit=256){return String(value??'').slice(0,limit)}
function frameTestNumber(value){const n=Number(value);return Number.isFinite(n)&&n>=0?n:undefined}
function frameTestActionProjection(action){
  const source=action&&typeof action==='object'?action:{},out={};
  for(const key of ['type','object_id','order_id','work_id','purchase_id','address','customer','customer_name','phone','object_status','order_title','order_status','work_name','new_name','unit','category','note','document_type','closure_id'])if(source[key]!==undefined)out[key]=frameTestString(source[key],key==='note'?2000:500);
  for(const key of ['qty','price','amount','progress_pct']){const n=frameTestNumber(source[key]);if(n!==undefined)out[key]=n}
  return out;
}
function frameTestActionsFromDraft(draft){
  const d=draft&&typeof draft==='object'?draft:{};if(Array.isArray(d.actions)&&d.actions.length)return d.actions;
  const [object_id='',order_id='']=String(d.targetKey||'').split('|'),target={object_id,order_id};
  if(d.type==='payment')return [{type:'add_payment',...target,amount:d.amount}];
  if(d.type==='expense')return [{type:'add_expense',...target,amount:d.amount,category:d.worker||'Исполнитель'}];
  if(d.type==='purchase')return [{type:'add_purchase',...target,amount:d.amount,work_name:d.name||'Материалы / расходники'}];
  if(d.type==='work_add')return [{type:'add_work',...target,work_name:d.work?.name,qty:d.work?.qty,unit:d.work?.unit,price:d.work?.price}];
  if(d.type==='work_complete')return [{type:'set_work_progress',...target,work_id:d.rowId,work_name:d.rowName,progress_pct:100}];
  if(d.type==='order_note')return [{type:'add_note',...target,note:d.note}];
  return [];
}
function frameTestDailyLimitsProjection(value){
  const source=value&&typeof value==='object'?value:{},out={};
  for(const key of ['date','utc_offset','hard_stop_reason'])if(source[key]!==undefined)out[key]=frameTestString(source[key],128);
  for(const key of ['spent_usd','reserved_usd','remaining_usd','budget_usd','calls_used','calls_remaining','call_cap']){const n=frameTestNumber(source[key]);if(n!==undefined)out[key]=n}
  return out;
}
function frameBuildTestTrace(draft,response,roundTripMs,errorCode=''){
  const d=draft&&typeof draft==='object'?draft:{},meta=response?.meta&&typeof response.meta==='object'?response.meta:{},result=response?.result&&typeof response.result==='object'?response.result:{},draftActions=frameTestActionsFromDraft(d),actions=draftActions.length?draftActions:(!d.blocked&&Array.isArray(result.actions)?result.actions:[]),trace={
    provider:frameTestString(meta.provider??d.provider,128),model:frameTestString(meta.model??d.model,128),mode:frameTestString(meta.mode??d.mode,64),
    outcome:d.blocked?'blocked':d.clarification?'clarification':d.ok?(actions.length?'proposed':'answer'):'error',
    target_key:frameTestString(d.targetKey,256),target_label:frameTestString(d.targetLabel,1000),
    proposed_actions:actions.map(frameTestActionProjection).filter(x=>x.type).slice(0,30),
    policy_blocked_actions:(Array.isArray(meta.policy_blocked_actions)?meta.policy_blocked_actions:(d.policyBlockedActions||[])).map(x=>frameTestString(x,128)).slice(0,30),
    web_search_used:meta.web_search_used===true,
    web_sources:(Array.isArray(meta.web_sources)?meta.web_sources:[]).map(x=>({title:frameTestString(x?.title||'Источник',200),url:frameTestString(x?.url,2000)})).filter(x=>/^https?:\/\//i.test(x.url)).slice(0,8)
  };
  const numeric={round_trip_ms:roundTripMs,provider_duration_ms:meta.duration_ms,input_tokens:meta.input_tokens,output_tokens:meta.output_tokens,estimated_usd:meta.estimated_usd,confidence:result.confidence??d.confidence};
  for(const [key,value] of Object.entries(numeric)){const n=frameTestNumber(value);if(n!==undefined)trace[key]=n}
  const limits=frameTestDailyLimitsProjection(meta.daily_limits);if(Object.keys(limits).length)trace.daily_limits=limits;
  if(meta.fallback_from)trace.fallback_from=frameTestString(meta.fallback_from,128);
  if(meta.limit_reason)trace.limit_reason=frameTestString(meta.limit_reason,128);
  if(meta.truthful_plan_guard)trace.truthful_plan_guard=frameTestString(meta.truthful_plan_guard,128);
  if(Array.isArray(meta.policy_reference_errors))trace.policy_reference_errors=meta.policy_reference_errors.map(x=>frameTestString(x,128)).slice(0,30);
  for(const [key,value] of Object.entries({web_search_calls:meta.web_search_calls,web_search_tool_usd:meta.web_search_tool_usd})){const n=frameTestNumber(value);if(n!==undefined)trace[key]=n}
  if(errorCode)trace.error_code=frameTestString(errorCode,128);
  return trace;
}
function frameTestTraceProjection(value){
  const source=value&&typeof value==='object'?value:{},trace={
    provider:frameTestString(source.provider,128),model:frameTestString(source.model,128),mode:frameTestString(source.mode,64),outcome:frameTestString(source.outcome,64),
    target_key:frameTestString(source.target_key,256),target_label:frameTestString(source.target_label,1000),
    proposed_actions:(Array.isArray(source.proposed_actions)?source.proposed_actions:[]).map(frameTestActionProjection).filter(x=>x.type).slice(0,30),
    policy_blocked_actions:(Array.isArray(source.policy_blocked_actions)?source.policy_blocked_actions:[]).map(x=>frameTestString(x,128)).slice(0,30),
    web_search_used:source.web_search_used===true,
    web_sources:(Array.isArray(source.web_sources)?source.web_sources:[]).map(x=>({title:frameTestString(x?.title||'Источник',200),url:frameTestString(x?.url,2000)})).filter(x=>/^https?:\/\//i.test(x.url)).slice(0,8)
  };
  for(const key of ['round_trip_ms','provider_duration_ms','input_tokens','output_tokens','estimated_usd','confidence','web_search_calls','web_search_tool_usd']){const n=frameTestNumber(source[key]);if(n!==undefined)trace[key]=n}
  const limits=frameTestDailyLimitsProjection(source.daily_limits);if(Object.keys(limits).length)trace.daily_limits=limits;
  for(const key of ['fallback_from','limit_reason','error_code','truthful_plan_guard'])if(source[key])trace[key]=frameTestString(source[key],128);
  if(Array.isArray(source.policy_reference_errors))trace.policy_reference_errors=source.policy_reference_errors.map(x=>frameTestString(x,128)).slice(0,30);
  return trace;
}
function frameTestMessageProjection(message,{expirePending=false}={}){
  if(!message||typeof message!=='object')return null;
  const role=message.role==='user'?'user':message.role==='assistant'?'assistant':'';if(!role)return null;
  const allowed=new Set(['done','pending','applied','cancelled','expired','error']),status=allowed.has(String(message.status||''))?String(message.status):'done';
  const item={id:frameTestString(message.id,128),turn_id:frameTestString(message.turnId??message.turn_id,128),at:frameTestString(message.at,64),role,text:frameTestString(message.text,FRAME_TEST_TEXT_LIMIT),status:expirePending&&status==='pending'?'expired':status};
  const trace=frameTestTraceProjection(message.trace);if(Object.values(trace).some(v=>Array.isArray(v)?v.length:typeof v==='object'?Object.keys(v).length:String(v||'').length))item.trace=trace;
  const links=(Array.isArray(message.links)?message.links:[]).map(link=>({kind:frameTestString(link?.kind,32),object_id:frameTestString(link?.objectId??link?.object_id,128),order_id:frameTestString(link?.orderId??link?.order_id,128),document_id:frameTestString(link?.documentId??link?.document_id,128),label:frameTestString(link?.label,160)})).filter(link=>link.kind).slice(0,8);if(links.length)item.links=links;
  if(message.receipt&&typeof message.receipt==='object')item.receipt=frameOwnerReceiptProjection(message.receipt);
  return item;
}
function frameOwnerDestination(value){const destination=String(value||'').toLowerCase();return /^[a-f0-9]{64}$/.test(destination)?destination:''}
function frameOwnerConsentLedger(value,fallbackDestination='',fallbackAt=''){
  const ledger=[],seen=new Set(),add=(entry,destinationFallback='',atFallback='')=>{const destination=frameOwnerDestination(entry?.destination||destinationFallback);if(!destination||seen.has(destination))return;const parsed=Date.parse(String(entry?.consented_at||atFallback||'')),consentedAt=Number.isFinite(parsed)?new Date(parsed).toISOString():new Date().toISOString();seen.add(destination);ledger.push({destination,consented_at:consentedAt})};
  for(const entry of Array.isArray(value)?value:[])add(entry);
  add(null,fallbackDestination,fallbackAt);
  return ledger.slice(-FRAME_OWNER_TEST_DESTINATION_LIMIT);
}
function frameOwnerRememberDestination(data,destination,at=''){if(!data)return;data.destination_consents=frameOwnerConsentLedger(data.destination_consents,destination,at)}
function frameOwnerActiveDestination(data){const destination=frameOwnerDestination(data?.remote_destination),current=frameOwnerDestination(aiBrainStatus?.ownerDestination);return data?.active===true&&data.remote_sync===true&&aiBrainStatus?.ok===true&&aiBrainStatus?.ownerTestObservability===true&&!!destination&&destination===current&&frameOwnerVerifiedCredential===frameOwnerCredentialKey()&&frameOwnerConsentLedger(data.destination_consents).some(item=>item.destination===destination)?destination:''}
function frameOwnerRecentMessage(message){const stamp=Date.parse(String(message?.at||''));return Number.isFinite(stamp)&&stamp>=Date.now()-FRAME_TEST_TRANSCRIPT_DAYS*86400000}
function frameTestTranscriptRead(){
  let raw;try{raw=JSON.parse(storageGet(FRAME_TEST_TRANSCRIPT_KEY,'')||'null')}catch(e){storageRemove(FRAME_TEST_TRANSCRIPT_KEY);return null}
  if(!raw||raw.format!==FRAME_TEST_TRANSCRIPT_FORMAT||raw.schema_version!==FRAME_TEST_TRANSCRIPT_SCHEMA){if(raw)storageRemove(FRAME_TEST_TRANSCRIPT_KEY);return null}
  const expires=Date.parse(String(raw.expires_at||''));if(Number.isFinite(expires)&&Date.now()>expires){storageRemove(FRAME_TEST_TRANSCRIPT_KEY);return null}
  const stalePage=!!raw.page_id&&raw.page_id!==FRAME_TEST_PAGE_ID,remoteDestination=frameOwnerDestination(raw.remote_destination),destinationConsents=frameOwnerConsentLedger(raw.destination_consents,remoteDestination,raw.updated_at||raw.started_at),messages=(Array.isArray(raw.messages)?raw.messages:[]).map(x=>frameOwnerMessageProjection(x,{expirePending:stalePage})).filter(frameOwnerRecentMessage).slice(-FRAME_CHAT_LIMIT),clean={format:FRAME_TEST_TRANSCRIPT_FORMAT,schema_version:FRAME_TEST_TRANSCRIPT_SCHEMA,app_version:frameTestString(raw.app_version,32),session_id:frameTestString(raw.session_id,128),event_seq:Math.max(0,Number(raw.event_seq)||0),page_id:FRAME_TEST_PAGE_ID,started_at:frameTestString(raw.started_at,64),updated_at:frameTestString(raw.updated_at,64),expires_at:frameTestString(raw.expires_at,64),active:raw.active===true,remote_sync:raw.remote_sync===true&&!!remoteDestination&&destinationConsents.some(item=>item.destination===remoteDestination),remote_destination:remoteDestination,destination_consents:destinationConsents,topic_key:frameTestString(raw.topic_key,256),topic_label:frameOwnerRedactString(raw.topic_label,1000),messages};
  const encoded=JSON.stringify(clean);if(encoded!==JSON.stringify(raw)){storageSet(FRAME_TEST_TRANSCRIPT_KEY,encoded);if(storageGet(FRAME_TEST_TRANSCRIPT_KEY,'')!==encoded)console.warn('[FRAME] test transcript pruning was not persisted')}return clean;
}
function frameOwnerCredentialKey(base=aiServerUrl?.(),token=aiServerToken?.()){return `${String(base||'').trim().replace(/\/$/,'')}\n${String(token||'')}`}
function frameTestTranscriptWrite(data){
  if(!data)return false;const updated=new Date(),remoteDestination=frameOwnerDestination(data.remote_destination),destinationConsents=frameOwnerConsentLedger(data.destination_consents,remoteDestination,data.updated_at||data.started_at),clean={format:FRAME_TEST_TRANSCRIPT_FORMAT,schema_version:FRAME_TEST_TRANSCRIPT_SCHEMA,app_version:typeof VERSION==='string'?VERSION:'',session_id:frameTestString(data.session_id,128),event_seq:Math.max(0,Number(data.event_seq)||0),page_id:FRAME_TEST_PAGE_ID,started_at:frameTestString(data.started_at,64),updated_at:updated.toISOString(),expires_at:new Date(updated.getTime()+FRAME_TEST_TRANSCRIPT_DAYS*86400000).toISOString(),active:data.active===true,remote_sync:data.remote_sync===true&&!!remoteDestination&&destinationConsents.some(item=>item.destination===remoteDestination),remote_destination:remoteDestination,destination_consents:destinationConsents,topic_key:frameTestString(data.topic_key,256),topic_label:frameOwnerRedactString(data.topic_label,1000),messages:(Array.isArray(data.messages)?data.messages:[]).map(frameOwnerMessageProjection).filter(frameOwnerRecentMessage).slice(-FRAME_CHAT_LIMIT)},encoded=JSON.stringify(clean);
  storageSet(FRAME_TEST_TRANSCRIPT_KEY,encoded);return storageGet(FRAME_TEST_TRANSCRIPT_KEY,'')===encoded;
}
function frameOwnerSecretToken(value){const text=String(value||'');return /^(?:gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|xox[baprs]-[A-Za-z0-9-]{10,}|AIza[0-9A-Za-z_-]{20,}|AKIA[0-9A-Z]{16}|(?:sk|pk|rk|api)[-_][A-Za-z0-9_-]{12,}|eyJ[A-Za-z0-9_-]{5,}\.[A-Za-z0-9_-]{5,}\.[A-Za-z0-9_-]{5,})$/.test(text)}
function frameOwnerSafeUrl(value){try{const url=new URL(String(value||'').slice(0,4000));if(!/^https?:$/.test(url.protocol))return '';url.username='';url.password='';url.hash='';url.pathname=url.pathname.split('/').map(part=>{try{return frameOwnerSecretToken(decodeURIComponent(part))?'[скрыто]':part}catch(e){return '[скрыто]'}}).join('/');for(const key of [...url.searchParams.keys()]){const values=url.searchParams.getAll(key);if(/(?:token|key|auth|secret|password|passwd|signature|credential|session|jwt|code)/i.test(key)||values.some(frameOwnerSecretToken)){url.searchParams.delete(key);url.searchParams.set(key,'[скрыто]')}}return url.href}catch(e){return ''}}
function frameOwnerRedactString(value,limit=FRAME_TEST_TEXT_LIMIT){
  let text=String(value??'');
  text=text.replace(/-----BEGIN [^-\r\n]*PRIVATE KEY-----[\s\S]*?-----END [^-\r\n]*PRIVATE KEY-----/gi,'[скрытый приватный ключ]');
  text=text.replace(/\b(?:Authorization\s*:\s*)?(?:Bearer|Basic)\s+[A-Za-z0-9._~+\/=:-]{6,}/gi,'[скрытая авторизация]');
  text=text.replace(/\b(?:gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|xox[baprs]-[A-Za-z0-9-]{10,}|AIza[0-9A-Za-z_-]{20,}|AKIA[0-9A-Z]{16}|(?:sk|pk|rk|api)[-_][A-Za-z0-9_-]{12,}|eyJ[A-Za-z0-9_-]{5,}\.[A-Za-z0-9_-]{5,}\.[A-Za-z0-9_-]{5,})\b/gi,'[скрытый секрет]');
  text=text.replace(/https?:\/\/[^\s<>"']+/gi,raw=>{const tail=(raw.match(/[),.;!?]+$/)||[''])[0],core=tail?raw.slice(0,-tail.length):raw,safe=frameOwnerSafeUrl(core);return `${safe||'[скрытая ссылка]'}${tail}`});
  text=text.replace(/(\b(?:access[_-]?token|refresh[_-]?token|session[_-]?token|api[_-]?key|client[_-]?secret|authorization|password|passwd|secret|signature|credential|jwt)\b\s*[:=]\s*)(?:"[^"\r\n]*"|'[^'\r\n]*'|[^\s,;&]+)/gi,'$1[скрыто]');
  text=text.replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[скрытая почта]').replace(/(?:\+?7|8)[\s().-]*\d{3}[\s().-]*\d{3}[\s.-]*\d{2}[\s.-]*\d{2}/g,'[скрытый телефон]');
  return text.slice(0,limit);
}
function frameOwnerPreScrubTrace(value){
  const source=value&&typeof value==='object'?value:{},trace={...source};
  for(const key of ['provider','model','mode','outcome','target_key','target_label','fallback_from','limit_reason','error_code','truthful_plan_guard'])if(typeof trace[key]==='string')trace[key]=frameOwnerRedactString(trace[key],key==='target_label'?1000:256);
  for(const key of ['policy_blocked_actions','policy_reference_errors'])if(Array.isArray(trace[key]))trace[key]=trace[key].map(item=>frameOwnerRedactString(item,128));
  if(trace.daily_limits&&typeof trace.daily_limits==='object'){trace.daily_limits={...trace.daily_limits};for(const key of ['date','utc_offset','hard_stop_reason'])if(typeof trace.daily_limits[key]==='string')trace.daily_limits[key]=frameOwnerRedactString(trace.daily_limits[key],128)}
  trace.proposed_actions=(Array.isArray(trace.proposed_actions)?trace.proposed_actions:[]).map(action=>{const item={...(action&&typeof action==='object'?action:{})};for(const key of Object.keys(item))if(typeof item[key]==='string')item[key]=frameOwnerRedactString(item[key],key==='note'?2000:500);return item});
  trace.web_sources=(Array.isArray(trace.web_sources)?trace.web_sources:[]).map(source=>({title:frameOwnerRedactString(source?.title||'Источник',200),url:frameOwnerSafeUrl(source?.url)})).filter(source=>source.url);
  return trace;
}
function frameOwnerMessageProjection(message,{expirePending=false}={}){if(!message||typeof message!=='object')return null;const preScrubbed={...message,text:frameOwnerRedactString(message.text),trace:frameOwnerPreScrubTrace(message.trace),links:(Array.isArray(message.links)?message.links:[]).map(link=>({...link,label:frameOwnerRedactString(link?.label,160)}))},clean=frameTestMessageProjection(preScrubbed,{expirePending});if(!clean)return null;clean.text=frameOwnerRedactString(clean.text);return clean}
function frameOwnerReceiptProjection(receipt){const source=receipt&&typeof receipt==='object'?receipt:{},actions=source.actionTypes??source.action_types,ids=source.entityIds??source.entity_ids??{};return {ok:source.ok===true,postcondition_verified:(source.postconditionVerified??source.postcondition_verified)===true,status:frameOwnerRedactString(source.status,32),target_key:frameOwnerRedactString(source.targetKey??source.target_key,256),target_label:frameOwnerRedactString(source.targetLabel??source.target_label,1000),chat_id:frameOwnerRedactString(source.chatId??source.chat_id,128),log_id:frameOwnerRedactString(source.logId??source.log_id,128),action_types:(Array.isArray(actions)?actions:[]).map(x=>frameOwnerRedactString(x,64)).slice(0,30),entity_ids:{object_id:frameOwnerRedactString(ids.objectId??ids.object_id,128),order_id:frameOwnerRedactString(ids.orderId??ids.order_id,128),work_id:frameOwnerRedactString(ids.workId??ids.work_id,128),document_id:frameOwnerRedactString(ids.documentId??ids.document_id,128)},links:(Array.isArray(source.links)?source.links:[]).map(link=>({kind:frameOwnerRedactString(link?.kind,32),object_id:frameOwnerRedactString(link?.objectId??link?.object_id,128),order_id:frameOwnerRedactString(link?.orderId??link?.order_id,128),document_id:frameOwnerRedactString(link?.documentId??link?.document_id,128),label:frameOwnerRedactString(link?.label,160)})).slice(0,8),error:frameOwnerRedactString(source.error,500)}}
function frameOwnerHash(value){let hash=2166136261;for(const ch of String(value||'')){hash^=ch.charCodeAt(0);hash=Math.imul(hash,16777619)}return (hash>>>0).toString(36)}
function frameOwnerByteLength(value){const text=typeof value==='string'?value:JSON.stringify(value);try{return new TextEncoder().encode(text).byteLength}catch(e){return new Blob([text]).size}}
async function frameOwnerCurrentDestination(base=aiServerUrl?.(),token=aiServerToken?.()){base=String(base||'').trim().replace(/\/$/,'');token=String(token||'');if(!base||!token||!globalThis.crypto?.subtle)return '';const bytes=new TextEncoder().encode(`${base}\n${token}`),digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function frameOwnerOutboxRead(){
  const stored=storageGet(FRAME_OWNER_TEST_OUTBOX_KEY,'');if(!stored)return [];
  try{const value=JSON.parse(stored),cutoff=Date.now()-FRAME_TEST_TRANSCRIPT_DAYS*86400000,items=Array.isArray(value)?value.filter(item=>{const stamp=Date.parse(String(item?.event?.client_at||''));return !!frameOwnerDestination(item?.destination)&&item?.event&&Number.isFinite(stamp)&&stamp>=cutoff}):[],encoded=JSON.stringify(items);if(encoded!==stored){storageSet(FRAME_OWNER_TEST_OUTBOX_KEY,encoded);if(storageGet(FRAME_OWNER_TEST_OUTBOX_KEY,'')!==encoded)console.warn('[FRAME] owner test outbox pruning was not persisted')}return items}catch(e){storageSet(FRAME_OWNER_TEST_OUTBOX_KEY,'[]');return []}
}
function frameOwnerOutboxWrite(items){if(!Array.isArray(items)||items.length>FRAME_OWNER_TEST_OUTBOX_LIMIT)return false;const encoded=JSON.stringify(items);storageSet(FRAME_OWNER_TEST_OUTBOX_KEY,encoded);return storageGet(FRAME_OWNER_TEST_OUTBOX_KEY,'')===encoded}
function frameOwnerDropSession(sessionId){const id=String(sessionId||'');return !id||frameOwnerOutboxWrite(frameOwnerOutboxRead().filter(item=>String(item?.event?.session_id||'')!==id))}
function frameOwnerPauseRemote(reason){const data=frameTestTranscriptRead();if(data?.remote_sync){data.remote_sync=false;frameTestTranscriptWrite(data);frameUpdateTestButton()}toast(reason||'Удалённая синхронизация теста приостановлена; локальная запись продолжается')}
function frameOwnerScheduleFlush(delay=180,{reset=false}={}){if(reset)frameOwnerRetryAttempt=0;clearTimeout(frameOwnerFlushTimer);frameOwnerFlushTimer=setTimeout(()=>{frameOwnerFlushTimer=null;frameOwnerFlush()},Math.max(0,delay))}
function frameOwnerScheduleRetry(){if(frameOwnerRetryAttempt>=FRAME_OWNER_TEST_RETRY_LIMIT)return false;const delay=Math.min(FRAME_OWNER_TEST_RETRY_MAX_MS,FRAME_OWNER_TEST_RETRY_BASE_MS*2**frameOwnerRetryAttempt);frameOwnerRetryAttempt++;frameOwnerScheduleFlush(delay);return true}
function frameOwnerEvent(message,typeOverride='',receipt=null){const data=frameTestTranscriptRead(),clean=frameOwnerMessageProjection(message),destination=frameOwnerActiveDestination(data);if(!destination||!clean)return null;const remoteMessage={...clean};delete remoteMessage.receipt;const type=typeOverride||(clean.role==='user'?'chat.user':clean.status==='applied'?'action.apply_result':clean.status==='cancelled'?'action.cancelled':'brain.response'),receiptSource=receipt||(message?.receipt&&typeof message.receipt==='object'?message.receipt:null),projectedReceipt=frameOwnerReceiptProjection(receiptSource),fingerprint=frameOwnerHash(JSON.stringify({type,message:remoteMessage,receipt:projectedReceipt}));data.event_seq=Math.max(0,Number(data.event_seq)||0)+1;if(!frameTestTranscriptWrite(data))return null;const payload={message:remoteMessage};if(receiptSource||type.startsWith('action.'))payload.receipt=projectedReceipt;return {destination,event:{schema_version:1,event_id:`${data.session_id}:${clean.id}:${clean.status}:${fingerprint}`,session_id:data.session_id,turn_id:clean.turn_id||'',seq:data.event_seq,client_at:new Date().toISOString(),app_version:typeof VERSION==='string'?VERSION:'',type,payload}}}
function frameOwnerQueueEvent(envelope){if(!envelope?.event||!frameOwnerDestination(envelope.destination))return false;if(frameOwnerByteLength(envelope.event)>FRAME_OWNER_TEST_MAX_EVENT_BYTES){frameOwnerPauseRemote('Событие теста слишком большое для безопасной передачи; локальная запись продолжается');return false}const items=frameOwnerOutboxRead();if(items.some(x=>x.destination===envelope.destination&&x.event.event_id===envelope.event.event_id)){frameOwnerScheduleFlush(180,{reset:true});return true}if(items.length>=FRAME_OWNER_TEST_OUTBOX_LIMIT){frameOwnerPauseRemote('Очередь теста заполнена; локальная запись продолжается, пока FRAME не восстановит связь');return false}items.push(envelope);if(!frameOwnerOutboxWrite(items)){frameOwnerPauseRemote('Не удалось надёжно сохранить очередь синхронизации; локальная запись продолжается');return false}frameOwnerScheduleFlush(180,{reset:true});return true}
function frameOwnerBatch(items,destination){const selected=[];for(const item of items){if(item.destination!==destination)continue;const next=[...selected,item];if(next.length>32||frameOwnerByteLength({events:next.map(x=>x.event)})>FRAME_OWNER_TEST_MAX_BATCH_BYTES)break;selected.push(item)}return selected}
async function frameOwnerFlush(){
  if(frameOwnerFlushBusy||aiBrainStatus?.ok!==true||aiBrainStatus?.ownerTestObservability!==true)return;
  const base=String(aiServerUrl?.()||'').trim().replace(/\/$/,''),token=String(aiServerToken?.()||''),credential=frameOwnerCredentialKey(base,token);if(!base||!token||credential!==frameOwnerVerifiedCredential)return;
  frameOwnerFlushBusy=true;
  try{const destination=await frameOwnerCurrentDestination(base,token);if(!destination||destination!==frameOwnerDestination(aiBrainStatus?.ownerDestination)||credential!==frameOwnerCredentialKey())return;const items=frameOwnerOutboxRead(),batch=frameOwnerBatch(items,destination);if(!batch.length){frameOwnerRetryAttempt=0;return}const response=await aiBrainFetch('/owner-test/v1/events',{method:'POST',body:JSON.stringify({events:batch.map(x=>x.event)})},{base,token}),expected=new Set(batch.map(x=>String(x.event.event_id))),acked=new Set((response?.acked_event_ids||[]).map(String).filter(id=>expected.has(id)));if(!acked.size)throw new Error('FRAME не подтвердил сохранение событий');const confirmedDeletes=batch.filter(item=>acked.has(String(item.event.event_id))&&item.event.type==='session.delete').length;if(!frameOwnerOutboxWrite(frameOwnerOutboxRead().filter(x=>x.destination!==destination||!acked.has(String(x.event.event_id)))))throw new Error('Не удалось обновить очередь после подтверждения');frameOwnerRetryAttempt=0;if(confirmedDeletes)toast(confirmedDeletes===1?'FRAME подтвердил удаление серверной копии':`FRAME подтвердил удаление серверных копий: ${confirmedDeletes}`);if(frameOwnerOutboxRead().some(x=>x.destination===destination))frameOwnerScheduleFlush(250)}catch(e){console.warn('[FRAME] owner test sync deferred',String(e?.message||e));frameOwnerScheduleRetry()}finally{frameOwnerFlushBusy=false}
}
function frameOwnerSessionEvent(type,session,destinationOverride=''){const data=session||frameTestTranscriptRead(),destination=frameOwnerDestination(destinationOverride||data?.remote_destination);if(!data?.session_id||!destination)return null;frameOwnerRememberDestination(data,destination,data.updated_at||data.started_at);if(type!=='session.delete'&&(!data.remote_sync||destination!==data.remote_destination))return null;data.event_seq=Math.max(0,Number(data.event_seq)||0)+1;if(!frameTestTranscriptWrite(data))return null;return {destination,event:{schema_version:1,event_id:`${data.session_id}:${type}:${destination.slice(0,16)}:${data.event_seq}`,session_id:data.session_id,turn_id:'',seq:data.event_seq,client_at:new Date().toISOString(),app_version:typeof VERSION==='string'?VERSION:'',type,payload:{}}}}
function frameOwnerSessionDestinations(data){const destinations=new Set(frameOwnerConsentLedger(data?.destination_consents,data?.remote_destination,data?.updated_at||data?.started_at).map(item=>item.destination));for(const item of frameOwnerOutboxRead())if(String(item?.event?.session_id||'')===String(data?.session_id||'')){const destination=frameOwnerDestination(item.destination);if(destination)destinations.add(destination)}return [...destinations]}
function frameOwnerReplaceSessionWithTombstones(data){if(!data?.session_id)return 0;const destinations=frameOwnerSessionDestinations(data);for(const destination of destinations)frameOwnerRememberDestination(data,destination,data.updated_at||data.started_at);const tombstones=destinations.map(destination=>frameOwnerSessionEvent('session.delete',data,destination)).filter(Boolean),retained=frameOwnerOutboxRead().filter(item=>String(item?.event?.session_id||'')!==String(data.session_id));if(retained.length+tombstones.length>FRAME_OWNER_TEST_OUTBOX_LIMIT||tombstones.some(item=>frameOwnerByteLength(item.event)>FRAME_OWNER_TEST_MAX_EVENT_BYTES)||!frameOwnerOutboxWrite([...retained,...tombstones]))return -1;if(tombstones.length)frameOwnerScheduleFlush(0,{reset:true});return tombstones.length}
function frameTestTranscriptActive(){return frameTestTranscriptRead()?.active===true}
function frameTestTranscriptSync(message,{eventType='',receipt=null}={}){
  const data=frameTestTranscriptRead();if(!data?.active)return;const actualReceipt=receipt||(message?.receipt&&typeof message.receipt==='object'?message.receipt:null)||(message?.status==='applied'?frameLastApplyReceipt:null),privateClean=frameOwnerMessageProjection(message);if(!privateClean)return;if(actualReceipt)privateClean.receipt=frameOwnerReceiptProjection(actualReceipt);
  const index=data.messages.findIndex(x=>x.id===privateClean.id);if(index>=0)data.messages[index]=privateClean;else data.messages.push(privateClean);
  data.topic_key=frameTestString(frameTopicSession,256);data.topic_label=frameOwnerRedactString(frameTopicLabel(),1000);if(!frameTestTranscriptWrite(data))return;
  frameOwnerQueueEvent(frameOwnerEvent({...message,receipt:actualReceipt||message?.receipt},eventType,actualReceipt));
}
async function frameStartTestTranscript(remoteSync=false){
  let data=frameTestTranscriptRead();const stamp=new Date().toISOString();
  if(!data)data={format:FRAME_TEST_TRANSCRIPT_FORMAT,schema_version:FRAME_TEST_TRANSCRIPT_SCHEMA,app_version:typeof VERSION==='string'?VERSION:'',session_id:typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():uid(),page_id:FRAME_TEST_PAGE_ID,started_at:stamp,updated_at:stamp,expires_at:stamp,active:true,remote_sync:false,remote_destination:'',destination_consents:[],topic_key:'',topic_label:'',messages:[]};
  if(remoteSync){const base=String(aiServerUrl?.()||'').trim().replace(/\/$/,''),token=String(aiServerToken?.()||''),credential=frameOwnerCredentialKey(base,token);if(aiBrainStatus?.ok!==true||aiBrainStatus?.ownerTestObservability!==true||credential!==frameOwnerVerifiedCredential){toast('Личный FRAME сейчас не подтвердил приём теста');return false}const destination=await frameOwnerCurrentDestination(base,token);if(!destination||credential!==frameOwnerCredentialKey()||destination!==frameOwnerDestination(aiBrainStatus?.ownerDestination)){toast('Настройки FRAME изменились — проверьте подключение и подтвердите синхронизацию заново');return false}frameOwnerRememberDestination(data,destination,stamp);data.remote_sync=true;data.remote_destination=destination}else{data.remote_sync=false;data.remote_destination=''}
  data.active=true;data.topic_key=frameTestString(frameTopicSession,256);data.topic_label=frameOwnerRedactString(frameTopicLabel(),1000);
  if(!frameTestTranscriptWrite(data)){toast('Не удалось включить запись на этом устройстве');return false}let queued=false;if(data.remote_sync)queued=frameOwnerQueueEvent(frameOwnerSessionEvent('session.start',data));frameUpdateTestButton();if(queued)frameOwnerScheduleFlush(0);toast(data.remote_sync&&queued?'Личная запись включена; отправка в ваш FRAME поставлена в очередь':'Личная запись включена только на этом устройстве');return true;
}
function frameStopTestTranscript(){const data=frameTestTranscriptRead();if(!data)return;const destination=data.remote_sync?data.remote_destination:'';data.active=false;if(!frameTestTranscriptWrite(data)){toast('Не удалось надёжно остановить запись');return}if(destination)frameOwnerQueueEvent(frameOwnerSessionEvent('session.stop',data,destination));frameUpdateTestButton();frameOwnerScheduleFlush(0);toast('Запись остановлена')}
function frameClearTestTranscript(){const data=frameTestTranscriptRead();let queued=0;if(data)queued=frameOwnerReplaceSessionWithTombstones(data);storageRemove(FRAME_TEST_TRANSCRIPT_KEY);frameUpdateTestButton();if(queued>0)toast(`Локальная копия удалена; удаление серверных копий поставлено в очередь: ${queued}`);else if(queued<0)toast('Локальная копия удалена, но не удалось надёжно поставить серверное удаление в очередь');else toast('Локальная копия удалена')}
function frameTranscriptPayload(){
  const stored=frameTestTranscriptRead(),messages=stored?stored.messages:frameChatMessages().map(frameTestMessageProjection).filter(Boolean);
  return {format:FRAME_TEST_TRANSCRIPT_FORMAT,schema_version:FRAME_TEST_TRANSCRIPT_SCHEMA,app_version:typeof VERSION==='string'?VERSION:'',exported_at:new Date().toISOString(),session_id:stored?.session_id||'',recording_started_at:stored?.started_at||'',recording_active:stored?.active===true,remote_sync:stored?.remote_sync===true,topic_key:stored?.topic_key||frameTestString(frameTopicSession,256),topic_label:stored?.topic_label||frameTestString(frameTopicLabel(),1000),message_count:messages.length,messages:messages.map(frameOwnerMessageProjection).filter(Boolean)};
}
async function frameExportTestTranscript(){
  const payload=frameTranscriptPayload();if(!payload.messages.length)return toast('Диалог пока пуст');
  const stamp=new Date().toISOString().replace(/[-:]/g,'').replace('T','-').slice(0,13),name=`FRAME-test-dialog-${stamp}.json`,text=JSON.stringify(payload,null,2),file=typeof File==='function'?new File([text],name,{type:'application/json'}):null;
  try{if(file&&navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'Тестовый диалог FRAME',files:[file]});toast('Диалог передан');return}}catch(e){if(e?.name==='AbortError')return}
  const blob=file||new Blob([text],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Файл диалога подготовлен');
}
function frameUpdateTestButton(){const button=$('frameTestBtn'),active=frameTestTranscriptActive();if(button){button.classList.toggle('active',active);button.innerHTML=`<i></i>${active?'ЗАПИСЬ':'ЛИЧНЫЙ ТЕСТ'}`;button.setAttribute('aria-label',active?'Личная тестовая запись включена':'Открыть личный тест')}}
function frameShowTestTranscript(){
  const data=frameTestTranscriptRead(),count=data?data.messages.length:0,active=data?.active===true;
  const remoteAvailable=aiBrainStatus?.ok===true&&aiBrainStatus?.ownerTestObservability===true&&frameOwnerVerifiedCredential===frameOwnerCredentialKey(),remoteConfigured=data?.remote_sync===true,remoteActive=!!frameOwnerActiveDestination(data);
  const startButtons=active?'':`${remoteAvailable?`<button id="frameStartRemoteTestBtn" class="btn primary">${data?'Продолжить и синхронизировать':'Записывать в мой FRAME'}</button>`:''}<button id="frameStartTestBtn" class="btn ${remoteAvailable?'ghost':'primary'}">${data?'Продолжить только здесь':'Только на устройстве'}</button>${count?'<button id="frameExportTestBtn" class="btn ghost">Поделиться текущим файлом</button>':''}`;
  const enableRemote=active&&remoteAvailable&&!remoteActive?'<button id="frameStartRemoteTestBtn" class="btn ghost">Включить синхронизацию</button>':'';
  openSheet(`<div class="sectionTitle"><div><h1>Личный тест</h1><p class="help compact">${active?'Запись включена.':data?'Запись остановлена.':'Запись ещё не включена.'} Это явный режим только для ваших тестов; по умолчанию он выключен.</p></div><button class="sheetCloseIcon" data-close-sheet aria-label="Закрыть">×</button></div><div class="frameTestSummary">Записано сообщений: <strong>${count}</strong><br><small>${remoteActive?'Новые события ставятся в очередь только для привязанного личного FRAME; серверные записи считаются сохранёнными лишь после подтверждения.':remoteConfigured?'Настройки FRAME изменились: новые события остаются здесь до нового согласия.':'Данные остаются только на этом устройстве.'}</small></div><div class="frameTestActions">${active?'<button id="frameExportTestBtn" class="btn primary">Поделиться файлом</button><button id="frameStopTestBtn" class="btn ghost">Остановить запись</button>':''}${enableRemote}${startButtons} ${data?'<button id="frameClearTestBtn" class="btn ghost dangerText">Удалить тестовый диалог</button>':''}</div><p class="help compact">Сохраняются сообщения, модель, задержка и подтверждённый результат действий. Сырой звук и адрес сервера не сохраняются; распознанные токены, ключи, почта и телефоны маскируются. Локальный срок — 7 дней.</p>`);
  if($('frameStartTestBtn'))$('frameStartTestBtn').onclick=async()=>{if(await frameStartTestTranscript(false)&&typeof closeSheet==='function')closeSheet()};
  if($('frameStartRemoteTestBtn'))$('frameStartRemoteTestBtn').onclick=async()=>{if(await frameStartTestTranscript(true)&&typeof closeSheet==='function')closeSheet()};
  if($('frameExportTestBtn'))$('frameExportTestBtn').onclick=frameExportTestTranscript;
  if($('frameStopTestBtn'))$('frameStopTestBtn').onclick=()=>{frameStopTestTranscript();if(typeof closeSheet==='function')closeSheet()};
  if($('frameClearTestBtn'))$('frameClearTestBtn').onclick=()=>{if(confirm('Удалить записанный тестовый диалог?')){frameClearTestTranscript();if(typeof closeSheet==='function')closeSheet()}};
}
frameTestTranscriptRead();frameOwnerOutboxRead();
function frameChatMessages(){return frameChatSession.slice()}
function frameProviderChatMessages(){return frameChatMessages().filter(x=>frameSessionMessageIds.has(String(x?.id||'')))}
function frameSaveChat(items){frameChatSession=(items||[]).slice(-FRAME_CHAT_LIMIT)}
function frameAddChat(message){const items=frameChatMessages(),item={id:uid(),at:now(),role:'assistant',status:'done',...message};frameSessionMessageIds.add(String(item.id));items.push(item);frameSaveChat(items);frameTestTranscriptSync(item);return item}
function frameUpdateChat(id,patch,syncOptions={}){const items=frameChatMessages(),i=items.findIndex(x=>x.id===id);if(i<0)return null;items[i]={...items[i],...patch};frameSaveChat(items);frameTestTranscriptSync(items[i],syncOptions);return items[i]}
function frameSavePending(draft){framePendingSession=draft||null}
function frameDraftPolicyError(d){try{const error=typeof aiFieldSafeDraftError==='function'?String(aiFieldSafeDraftError(d)||''):'';if(error)return error;if(aiEffectiveMode(d?.mode)==='field_safe'&&Array.isArray(d.actions)&&d.actions.length&&!String(d.targetLabel||'').trim())return 'FRAME заблокировал старый план без зафиксированной цели. Ничего не применено.';return ''}catch(e){return 'FRAME не смог проверить безопасность плана. Ничего не применено.'}}
function frameRestorePending(){if(aiDraft?.ok){if(!frameDraftPolicyError(aiDraft))return aiDraft;aiDraft=null;frameClearPending()}const d=framePendingSession;if(d?.ok){if(frameDraftPolicyError(d)){frameClearPending();return null}aiDraft=d;return d}return null}
function frameClearPending(){framePendingSession=null}
function frameClearPendingIf(id=''){if(!id||String(framePendingSession?.chatId||'')===String(id)){framePendingSession=null;if(String(aiDraft?.chatId||'')===String(id))aiDraft=null}}
function frameChatTime(v){try{return new Date(v).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}catch(e){return ''}}
function frameTopic(){return frameTopicSession}
function frameSetTopic(key=''){if(!key){frameTopicSession='';routeState.aiTarget='';return}if(aiTargetByKey(key)){frameTopicSession=key;routeState.aiTarget=key;const data=frameTestTranscriptRead();if(data?.active){data.topic_key=frameTestString(key,256);data.topic_label=frameTestString(frameTopicLabel(),1000);frameTestTranscriptWrite(data)}}}
const FRAME_TARGET_GENERIC=new Set(['монтаж','работа','работы','работам','готова','готов','поставь','поставить','процент','процентов']);
function frameWorkTargetScore(order,text=''){const tokens=aiTokens(text).filter(x=>x.length>=4&&!FRAME_TARGET_GENERIC.has(x));let best=0;for(const row of order?.works||[]){const name=aiNorm(row.name),nameTokens=aiTokens(name);let score=0;for(const token of tokens){if(name.includes(token))score+=3;else if(nameTokens.some(x=>x.startsWith(token)||token.startsWith(x)))score+=2}best=Math.max(best,score)}return best}
function frameDetectTarget(text=''){const norm=aiNorm(text),tokens=aiTokens(norm),addingWork=/(?:добавь|добавить|допработ|новая\\s+работа)/.test(norm);let best='',bestScore=0,tied=false;for(const x of aiAllTargets()){const hay=aiNorm(`${x.object.contact.address} ${x.object.contact.name} ${x.order.title}`);let score=0;for(const token of tokens){if(token.length>=4&&hay.includes(token))score+=2}for(const p of aiNorm(x.object.contact.address).split(' ')){const s=aiStem(p);if(s.length>=5&&norm.includes(s))score+=4}if(!addingWork)score+=frameWorkTargetScore(x.order,norm);if(score>bestScore){bestScore=score;best=x.key;tied=false}else if(score===bestScore&&score>0&&best!==x.key)tied=true}return bestScore>=3&&!tied?best:''}
function frameTopicLabel(){const t=aiTargetByKey(frameTopic());return t?(t.object.contact.address||t.order.title||''):''}
function frameTargetLabel(key=''){const t=aiTargetByKey(String(key||''));if(!t)return '';return [t.object?.contact?.address,t.order?.title].map(x=>String(x||'').trim()).filter(Boolean).join(' · ')}
function frameUniqueNamedTarget(text=''){const tokens=frameOpenIdentityTokens(text);if(!tokens.length)return '';let best=0,matches=[];for(const target of aiAllTargets()){const hay=aiNorm(`${target.object.contact.address} ${target.object.contact.name} ${target.order.title}`),score=tokens.filter(token=>hay.includes(token)).length;if(score>best){best=score;matches=[target]}else if(score===best&&score>0)matches.push(target)}return best>0&&matches.length===1?matches[0].key:''}
function frameOpenIdentityTokens(text=''){return aiTokens(text).filter(token=>token.length>=3&&!/^(?:откр|покаж|найд|хоч|посмотр|дай|дайте|скинь|ссыл|карточ|объект|заказ|работ|позици|расценк|смет|фот|сним|галер|альбом|документ|акт|договор|счет|кп|предлож|переч|этому|этот|этой|текущ|закрыт|номер|последн)/.test(token))}
function frameResolveNamedObject(text=''){const tokens=frameOpenIdentityTokens(text),numbers=(aiNorm(text).match(/\d+[a-zа-я]?/g)||[]);if(!tokens.length)return {named:false,objectId:'',ambiguous:false};const seen=new Map();for(const target of aiAllTargets())if(!seen.has(target.object.id))seen.set(target.object.id,target.object);const scored=[];for(const object of seen.values()){const hay=aiNorm(`${object.contact?.address||''} ${object.contact?.name||''}`),objectTokens=aiTokens(hay),hits=tokens.filter(token=>hay.includes(token)||objectTokens.some(value=>value.startsWith(token)||token.startsWith(value))).length,addressNumbers=aiNorm(object.contact?.address||'').match(/\d+[a-zа-я]?/g)||[];if(!hits)continue;if(numbers.length&&addressNumbers.length&&!numbers.some(value=>addressNumbers.includes(value)))continue;scored.push({id:object.id,score:hits+(numbers.some(value=>addressNumbers.includes(value))?4:0)})}const best=Math.max(0,...scored.map(item=>item.score)),matches=scored.filter(item=>item.score===best);return {named:scored.length>0,objectId:matches.length===1?matches[0].id:'',ambiguous:matches.length>1}}
function framePreferredTargetKeyForObject(objectId,exactKey=''){const targets=aiAllTargets().filter(target=>target.object.id===String(objectId||'')),exact=targets.find(target=>target.key===exactKey),sticky=targets.find(target=>target.key===frameTopic()),active=targets.filter(target=>['agreed','work','awaiting','paused'].includes(String(target.order?.status||'')));return (exact||sticky||active.at(-1)||targets.at(-1)||{}).key||''}
function frameHasCyrillicTerm(text,pattern){return new RegExp(`(?:^|[^a-zа-яё0-9_])(?:${pattern})(?=$|[^a-zа-яё0-9_])`,'i').test(String(text||''))}
function frameAttachTargetSnapshot(d){if(d?.ok&&aiEffectiveMode(d.mode)==='field_safe'&&Array.isArray(d.actions)&&d.actions.length&&!String(d.targetLabel||'').trim())d.targetLabel=frameTargetLabel(d.targetKey);return d}
function framePlanHtml(d){if(!d?.actions?.length)return '';const target=aiEffectiveMode(d.mode)==='field_safe'&&d.targetLabel?`<div class="frameChatPlanRow frameChatPlanTarget"><span>Объект: <strong>${esc(d.targetLabel)}</strong></span></div>`:'';return `<div class="frameChatPlan">${target}${d.actions.map(a=>`<div class="frameChatPlanRow"><span>${esc(aiBrainActionSummary(a))}</span></div>`).join('')}</div>`}
function framePendingControls(m){return `<div class="frameChatActions"><button class="btn primary" data-chat-apply="${esc(m.id)}">Применить</button><button class="btn ghost" data-chat-cancel="${esc(m.id)}">Отмена</button></div>`}
function frameChatLinksHtml(message){const links=Array.isArray(message?.links)?message.links:[];if(!links.length)return '';return `<div class="frameChatLinks">${links.map((link,index)=>`<button type="button" data-chat-message="${esc(message.id)}" data-chat-link="${index}">${esc(link?.label||'Открыть')}</button>`).join('')}</div>`}
function frameChatSourcesHtml(message){const sources=Array.isArray(message?.sources)?message.sources:[];if(!sources.length)return '';return `<div class="frameChatSources">${sources.map(source=>{let href='';try{const url=new URL(String(source?.url||''));if(/^https?:$/.test(url.protocol))href=url.href}catch(e){}return href?`<a href="${esc(href)}" target="_blank" rel="noopener noreferrer">${esc(source?.title||'Источник')}</a>`:''}).join('')}</div>`}
function frameOpenChatLink(messageId,index){const message=frameChatMessages().find(x=>String(x.id)===String(messageId)),link=message?.links?.[Number(index)];if(!link)return toast('Ссылка больше не доступна');if(link.kind==='object')return frameOpenObjectRef(link.objectId,link.orderId);if(link.kind==='object_photos')return frameOpenObjectPhotosRef(link.objectId,link.orderId);if(['order','works','photos','documents'].includes(link.kind))return frameOpenOrderRef(link.objectId,link.orderId,link.kind==='order'?'order':link.kind);if(link.kind==='document'){const object=objects.find(o=>o.id===String(link.objectId||'')),order=object?.orders?.find(o=>o.id===String(link.orderId||'')),doc=order?.documentHistory?.find(d=>d.id===String(link.documentId||''));if(!object||!order||!doc)return toast('Документ больше не найден');if(!['proposal','worklist','act'].includes(doc.type))return frameOpenOrderRef(object.id,order.id,'documents');currentObjectId=object.id;currentOrderId=order.id;const key=`${object.id}|${order.id}`;routeState.aiTarget=key;frameSetTopic(key);buildOrderDocument(doc.type,(doc.snapshot||[]).map(clone),doc.options||{});return}toast('FRAME заблокировал неизвестную ссылку')}
function frameAppliedSummary(draft,receipt){const types=new Set(receipt?.actionTypes||[]);if(types.has('create_document'))return 'Готово, документ сохранён. Вот ссылка.';if(types.has('create_object'))return 'Готово, карточка объекта создана.';if(types.has('create_order'))return 'Готово, заказ создан.';if(types.has('add_work'))return 'Готово, работы записаны.';if(types.has('set_work_progress'))return 'Готово, прогресс обновлён.';if(types.has('add_note'))return 'Готово, заметка записана.';return `Готово, изменения записаны (${Math.max(1,types.size)}).`}
function frameLocalOpenIntent(text){
  const raw=String(text||''),norm=aiNorm(raw),subject=/(?:карточк|объект|заказ|работ|позици|расценк|смет|фото|фотограф|снимк|галере|альбом|документ|акт|договор|сч[её]т|кп|предложени|переч)/.test(norm),open=/(?:открой|открыть|покажи|показать|найди|найти|хочу\s+посмотреть|дай|дайте|скинь|ссылк|где\s+(?:фото|фотографии|снимки))/.test(norm);if(!open||!subject)return null;
  const exactKey=frameUniqueNamedTarget(raw),objectResolution=frameResolveNamedObject(raw);let key=exactKey;if(objectResolution.named&&objectResolution.objectId)key=framePreferredTargetKeyForObject(objectResolution.objectId,aiTargetByKey(exactKey)?.object?.id===objectResolution.objectId?exactKey:'');else if(objectResolution.named&&!exactKey)return {text:objectResolution.ambiguous?'Нашла несколько похожих объектов. Назови улицу и номер дома.':'Такой объект не нашла. Проверь адрес или имя заказчика.',links:[]};key=key||frameTopic()||(aiAllTargets().length===1?aiAllTargets()[0].key:'');if(!key)return {text:'Какой именно объект открыть? Назови адрес или заказчика — я сразу дам ссылку.',links:[]};
  const target=aiTargetByKey(key);if(!target)return {text:'Эта карточка больше не найдена. Назови другой адрес.',links:[]};frameSetTopic(key);const objectId=target.object.id,orderId=target.order.id,address=target.object.contact.address||target.order.title||'объект';
  if(/(?:фото|фотограф|снимк|галере|альбом)/.test(norm)){const albums=(target.object.orders||[]).flatMap(order=>(order.photos||[]).map(photo=>({photo,order}))),last=albums.slice().sort((a,b)=>String(a.photo.addedAt||a.photo.date||'').localeCompare(String(b.photo.addedAt||b.photo.date||''))).at(-1),stamp=last?.photo?.addedAt||last?.photo?.date||'';return {text:albums.length?`Нашла ${albums.length} фото по объекту «${address}»${stamp?` — последнее добавлено ${new Date(stamp).toLocaleString('ru-RU')}`:''}.`:`По объекту «${address}» фотографий пока нет.`,links:[{kind:'object_photos',objectId,orderId,label:'Открыть галерею объекта'}]}}
  if(/(?:работ|позици|расценк|смет)/.test(norm))return {text:`Вот работы по объекту «${address}».`,links:[{kind:'works',objectId,orderId,label:'Открыть работы'}]};
  if(/(?:документ|акт|договор|сч[её]т|кп|предложени|переч)/.test(norm)){const wanted=frameHasCyrillicTerm(norm,'акт(?:а|у|ом|е|ы|ов)?')?'act':/(?:перечень|перечн)/.test(norm)?'worklist':frameHasCyrillicTerm(norm,'кп')||/(?:коммерческ|предложени)/.test(norm)?'proposal':/договор/.test(norm)?'contract':/сч[её]т/.test(norm)?'invoice':'',entries=(target.object.orders||[]).flatMap(order=>(order.documentHistory||[]).map(doc=>({doc,order}))).sort((a,b)=>String(a.doc.date||'').localeCompare(String(b.doc.date||''))),matching=wanted?entries.filter(entry=>entry.doc.type===wanted):entries,supported=new Set(['proposal','worklist','act']),entry=[...matching].reverse().find(item=>supported.has(item.doc.type)),fallbackOrders=(target.object.orders||[]).filter(order=>(order.documentHistory||[]).length).slice(-4).map(order=>({kind:'documents',objectId,orderId:order.id,label:`Документы · ${order.title||'заказ'}`}));if(wanted&&!matching.length)return {text:`По объекту «${address}» документа «${docTypeLabel(wanted)}» пока нет.`,links:fallbackOrders.length?fallbackOrders:[{kind:'documents',objectId,orderId,label:'Открыть документы заказа'}]};if(entry)return {text:`Нашла ${wanted?docTypeLabel(wanted).toLowerCase():'документ'} по объекту «${address}».`,links:[{kind:'document',objectId,orderId:entry.order.id,documentId:entry.doc.id,label:`Открыть ${docTypeLabel(entry.doc.type).toLowerCase()}`},...fallbackOrders.slice(0,3)]};return {text:matching.length?`Нашла документы по объекту «${address}».`:`У объекта «${address}» сохранённых документов пока нет.`,links:fallbackOrders.length?fallbackOrders:[{kind:'documents',objectId,orderId,label:'Открыть документы заказа'}]}}
  if(/заказ/.test(norm)&&!/(?:карточк|объект)/.test(norm))return {text:`Вот заказ «${target.order.title||address}».`,links:[{kind:'order',objectId,orderId,label:'Открыть заказ'}]};
  return {text:`Вот карточка объекта «${address}».`,links:[{kind:'object',objectId,orderId,label:'Открыть объект'}]};
}
function frameLooksMutationRequest(text=''){const norm=aiNorm(text);return /(?:создай|создать|создавай|заведи|завести|добавь|добавить|запиши|записать|внеси|внести|сохрани|сохранить|измени|изменить|поменяй|поменять|обнови|обновить|удали|удалить|отметь|отметить|поставь|поставить|закрой|закрыть)/.test(norm)||/(?:сделай|сформируй|сформировать|подготовь|подготовить|оформи|оформить|составь|составить|сгенерируй|сгенерировать|выкати|выкатить|давай)[^.!?]{0,120}(?:карточк|объект|заказ|документ|акт|договор|сч[её]т|кп|предложени|переч)/.test(norm)||/(?:документ|акт|кп|коммерческ[^.!?]{0,30}предложени|переч)[^.!?]{0,100}(?:сделай|сформируй|подготовь|оформи|составь|сгенерируй|выкати)/.test(norm)}
function frameAffirmsClarification(text=''){return /^(?:да|ага|угу|верно|точно|давай|создавай|делай|оформляй|записывай|сохраняй)(?:[\s,.!].*)?$/.test(aiNorm(text))}
function frameThinkingHtml(){return frameThinking?`<article class="frameChatMessage fromFrame frameThinking"><div class="frameChatBubble"><div class="frameThinkingRow"><span>FRAME думает</span><i></i><i></i><i></i></div></div></article>`:''}
function frameLatestUndoLogId(){return String([...aiLogs()].reverse().find(log=>!log.undone&&!log.undoPending)?.id||'')}
function frameChatHtml(){const items=frameChatMessages(),latestUndo=frameLatestUndoLogId();const body=!items.length?`<div class="frameChatWelcome"><span class="frameChatOrb">✦</span><div><strong>Здорово! Я Мира, помощница в FRAME.</strong><p>Могу вести объекты и расчёты, находить карточки и фотографии, готовить документы, искать свежую информацию и просто нормально поговорить. Скажи как есть — разберёмся.</p></div></div>`:items.map(m=>{const p=m.role==='assistant'&&m.status==='pending'&&m.draft,s=m.status==='applied'?'✓ Записано':m.status==='cancelled'?'Отменено':m.status==='error'?'Не выполнено':'',logId=String(m.receipt?.logId||''),undo=m.status==='applied'&&logId&&logId===latestUndo;return `<article class="frameChatMessage ${m.role==='user'?'fromUser':'fromFrame'} ${p?'hasPlan':''}"><div class="frameChatBubble"><small class="frameChatTime">${esc(frameChatTime(m.at))}</small><div class="frameChatText">${esc(m.text||'')}</div>${frameChatSourcesHtml(m)}${p?framePlanHtml(m.draft):''}${p?framePendingControls(m):''}${frameChatLinksHtml(m)}${s?`<div class="frameChatStatus ${m.status}">${s}${undo?` <button type="button" data-chat-undo="${esc(logId)}" data-chat-message="${esc(m.id)}">Отменить</button>`:''}</div>`:''}</div></article>`}).join('');return body+frameThinkingHtml()}
function frameScrollChat(){requestAnimationFrame(()=>{const x=$('frameChatFeed');if(x)x.scrollTop=x.scrollHeight})}
function frameRefreshChat(){const f=$('frameChatFeed');if(f)f.innerHTML=frameChatHtml();frameBindChatActions();frameScrollChat()}
function frameCancelPending(id=''){const d=frameRestorePending();if(d)aiRevokeDraftAuthorization(d);if(id)frameUpdateChat(id,{status:'cancelled',draft:null});else if(d?.chatId)frameUpdateChat(d.chatId,{status:'cancelled',draft:null});aiDraft=null;frameClearPending();frameRefreshChat()}
async function frameUndoChatAction(messageId,logId){const message=frameChatMessages().find(item=>String(item.id)===String(messageId));if(!message)return toast('Сообщение больше не найдено');const receipt=await undoLastAiAction(logId);if(receipt?.ok){frameUpdateChat(message.id,{status:'cancelled',text:'Отменила это изменение. Данные возвращены в прежнее состояние.',links:[],receipt},{eventType:'action.undo_result',receipt});frameRefreshChat()}else frameTestTranscriptSync(message,{eventType:'action.undo_result',receipt})}
function frameBindChatActions(){$$('[data-chat-apply]').forEach(b=>{const d=frameRestorePending();if(!d||d.chatId!==b.dataset.chatApply||!aiBindDisplayedDraftApply(b,d,async authorization=>{if(frameApplyingDraftId)return toast('FRAME уже применяет этот план');frameApplyingDraftId=d.chatId;b.disabled=true;$$('[data-chat-cancel]').forEach(x=>x.disabled=true);try{aiDraft=d;await applyAiDraft(authorization)}finally{frameApplyingDraftId=''}})){b.disabled=true;b.title='Этот план уже не активен'}});$$('[data-chat-cancel]').forEach(b=>b.onclick=()=>frameCancelPending(b.dataset.chatCancel));$$('[data-chat-undo]').forEach(b=>b.onclick=()=>frameUndoChatAction(b.dataset.chatMessage,b.dataset.chatUndo));$$('[data-chat-link]').forEach(b=>b.onclick=()=>frameOpenChatLink(b.dataset.chatMessage,b.dataset.chatLink))}

const frameCoreContextPayload=aiContextPayload;
aiContextPayload=function(){const topic=frameTopic();if(topic)routeState.aiTarget=topic;const base=frameCoreContextPayload(),currentTarget=topic||String(base?.current_target||''),conversation=frameProviderChatMessages().slice(-24).map(m=>({role:m.role==='user'?'user':'assistant',content:String(m.text||''),status:m.status||'done'}));return {...base,current_target:currentTarget,conversation_target:frameTopicLabel()||frameTargetLabel(currentTarget),conversation,conversation_rules:['The conversation_target is locked until the user explicitly names another object.','Pronouns like this object, here, these works and considering the above always refer to conversation_target.','Recent user facts in conversation are newer than stored progress until actions are applied.','Never switch to another object/order merely because it exists in context.']}}

checkAiBrain=async function({toastResult=true}={}){const base=aiServerUrl(),token=aiServerToken(),credential=frameOwnerCredentialKey(base,token),current=()=>base===aiServerUrl()&&token===aiServerToken();frameOwnerVerifiedCredential='';if(!base){aiRecordAuthenticatedHealth('',{url:base,authenticated:false});aiBrainStatus={ok:false,ownerTestObservability:false,ownerDestination:'',message:'Адрес не задан'};return aiBrainStatus}try{const d=await aiBrainFetch('/health',{method:'GET'},{base,token});if(!current())return aiBrainStatus||{ok:false,message:'Настройки AI Brain изменились'};const healthMode=String(d.mode||d.detail?.mode||''),fieldVerified=aiRecordAuthenticatedHealth(healthMode,{url:base,authenticated:!!token&&!!d.ok}),ok=!!d.ok&&(!aiConfiguredFieldSafe(base)||fieldVerified),ownerTestObservability=ok&&d.owner_test_observability===true,ownerDestination=ownerTestObservability?await frameOwnerCurrentDestination(base,token):'';if(!current())return aiBrainStatus||{ok:false,message:'Настройки AI Brain изменились'};frameOwnerVerifiedCredential=ownerTestObservability?credential:'';aiBrainStatus={ok,provider:d.provider||'',model:d.model||'',mode:healthMode,detail:d.detail||{},ownerTestObservability,ownerDestination,message:ok?'Готов к работе':aiConfiguredFieldSafe(base)?'Безопасный режим сервера не подтверждён':'AI Brain пока не готов'};if(ownerTestObservability)frameOwnerScheduleFlush(0,{reset:true});if(toastResult)toast(ok?'FRAME на связи':aiBrainStatus.message);return aiBrainStatus}catch(e){if(!current())return aiBrainStatus||{ok:false,message:'Настройки AI Brain изменились'};frameOwnerVerifiedCredential='';aiRecordAuthenticatedHealth('',{url:base,authenticated:false});aiBrainStatus={ok:false,ownerTestObservability:false,ownerDestination:'',message:String(e?.message||e)};if(toastResult)toast('FRAME не может связаться с AI Brain');return aiBrainStatus}finally{if(route==='ai')requestAnimationFrame(frameRenderConnectionDot)}};
window.addEventListener('online',()=>{frameOwnerRetryAttempt=0;frameOwnerScheduleFlush(0)});
function frameRenderConnectionDot(){const d=$('frameConnectionDot');if(d)d.className=`frameConnectionDot ${aiBrainStatus?.ok?'ok':aiBrainStatus?'bad':'wait'}`}
renderAiView=function(){frameRestorePending();if(!frameTopic()){const preferred=routeState.aiTarget||aiDefaultTargetKey();if(preferred&&aiTargetByKey(preferred))frameSetTopic(preferred)}const mic=!!(window.SpeechRecognition||window.webkitSpeechRecognition),recording=frameTestTranscriptActive();return `<section class="frameChatView"><header class="frameChatTop"><div class="frameChatTitle">FRAME <i id="frameConnectionDot" class="frameConnectionDot ${aiBrainStatus?.ok?'ok':aiBrainStatus?'bad':'wait'}"></i><small>${esc(frameTopicLabel()||'готова помочь')}</small></div><button id="frameTestBtn" class="frameTestButton ${recording?'active':''}" type="button" aria-label="${recording?'Личная тестовая запись включена':'Открыть личный тест'}"><i></i>${recording?'ЗАПИСЬ':'ЛИЧНЫЙ ТЕСТ'}</button></header><main id="frameChatFeed" class="frameChatFeed">${frameChatHtml()}</main><footer class="frameChatComposer"><button id="frameAttachBtn" class="frameComposerIcon" type="button" aria-label="Добавить">＋</button><div class="frameComposerField"><textarea id="aiCommandInput" rows="1" placeholder="Сообщение FRAME"></textarea><div id="frameVoicePanel" class="frameVoicePanel" hidden><span class="frameVoiceBars" aria-hidden="true">${Array.from({length:13},(_,i)=>`<i style="--bar:${i}"></i>`).join('')}</span><strong>Слушаю…</strong><small id="frameVoiceTimer">00:00</small></div></div><button id="aiMicBtn" class="frameComposerIcon mic" type="button" ${mic?'':'disabled'} aria-label="${mic?'Начать диктовку':'Диктовка недоступна'}">🎙️</button><button id="aiAnalyzeBtn" class="frameSendBtn" type="button" aria-label="Отправить">↑</button></footer></section>`}
function frameAutoGrowInput({keepCaret=false}={}){const i=$('aiCommandInput');if(!i)return;const wasAtEnd=i.selectionEnd===i.value.length;i.style.height='auto';const height=Math.min(132,i.scrollHeight);i.style.height=height+'px';i.style.overflowY=i.scrollHeight>132?'auto':'hidden';if(keepCaret){const end=i.value.length;try{i.setSelectionRange(end,end)}catch(e){}}if(keepCaret||wasAtEnd)requestAnimationFrame(()=>{i.scrollTop=i.scrollHeight})}
function frameSetComposerText(value){const input=$('aiCommandInput');if(!input)return;input.value=String(value||'');frameAutoGrowInput({keepCaret:true})}
function frameShowAttachMenu(){openSheet(`<div class="sectionTitle"><div><h1>Добавить</h1><p class="help compact">Фото, чек и файлы подключим здесь.</p></div><button class="sheetCloseIcon" data-close-sheet>×</button></div>`)}

function frameHardClearComposer(){frameVoiceBase='';frameVoiceFinal='';frameVoiceInterim='';frameComposerDraftSession='';const i=$('aiCommandInput');if(i){i.value='';i.style.height='auto';i.style.overflowY='hidden'}}
analyzeAiInput=async function(){
  if(aiAnalyzing||frameThinking)return toast('FRAME уже отвечает — секунду');
  if(frameApplyingDraftId)return toast('FRAME записывает изменение — секунду');
  aiAnalyzing=true;const btn=$('aiAnalyzeBtn');if(btn){btn.disabled=true;btn.textContent='…'}let turnId='',started=performance.now();
  try{
    if(frameVoiceWanted||aiRecognition||frameVoiceStopping)await frameStopVoice(true,true);
    const input=$('aiCommandInput'),text=String(input?.value||frameComposerDraftSession||'').trim();if(!text){toast('Сначала скажите или напишите сообщение');return}
    frameVoiceSession++;frameHardClearComposer();
    const detected=frameDetectTarget(text);if(detected)frameSetTopic(detected);else if(frameTopic())routeState.aiTarget=frameTopic();
    const old=frameRestorePending();if(old?.chatId){aiRevokeDraftAuthorization(old);frameUpdateChat(old.chatId,{status:'cancelled',draft:null})}aiDraft=null;frameClearPending();
    const previousMutation=frameMutationClarificationSession,directMutation=frameLooksMutationRequest(text),mutationIntent=directMutation||(!!previousMutation&&frameAffirmsClarification(text));frameMutationClarificationSession='';
    turnId=uid();started=performance.now();frameAddChat({role:'user',text,status:'done',turnId});frameThinking=true;frameRefreshChat();
    const localOpen=mutationIntent?null:frameLocalOpenIntent(text);
    if(localOpen){frameAddChat({role:'assistant',text:localOpen.text,status:'done',turnId,links:localOpen.links,trace:{provider:'FRAME local navigation',model:VERSION,mode:'local',outcome:'answer',round_trip_ms:Math.round(performance.now()-started),proposed_actions:[],policy_blocked_actions:[]}});return}
    let draft,response=null;if(aiServerUrl()){response=await requestAiBrain(text);if(mutationIntent)response={...response,meta:{...(response?.meta||{}),mutation_intent:true}};draft=brainDraftFromResponse(text,response)}else draft=parseAiCommand(text,frameTopic()||routeState.aiTarget);
    if(draft?.targetKey&&aiTargetByKey(draft.targetKey)){const explicit=frameDetectTarget(text);if(explicit)frameSetTopic(explicit);else if(frameTopic())draft.targetKey=frameTopic()}
    frameAttachTargetSnapshot(draft);const policyError=frameDraftPolicyError(draft);if(policyError)draft={...draft,ok:false,source:'brain',blocked:true,error:policyError,text};
    if(draft?.clarification&&mutationIntent)frameMutationClarificationSession=directMutation?text:previousMutation;const trace=frameBuildTestTrace(draft,response,Math.round(performance.now()-started));
    if(draft?.ok&&draft.type==='read_answer')frameAddChat({role:'assistant',text:draft.summary,status:'done',turnId,trace,sources:draft.sources||[]});
    else if(draft?.ok){const m=frameAddChat({role:'assistant',text:'Я поняла. Проверь, что именно записать:',status:'pending',draft,turnId,trace});draft.chatId=m.id;m.draft.chatId=m.id;frameUpdateChat(m.id,{draft:m.draft});aiDraft=draft;frameSavePending(draft)}
    else frameAddChat({role:'assistant',text:draft?.error||'Не разобрала конкретный фрагмент. Скажите его чуть иначе?',status:draft?.blocked?'error':'done',turnId,trace,sources:draft?.sources||[]});
  }catch(e){console.error(e);if(turnId)frameAddChat({role:'assistant',text:'Не смогла связаться с FRAME. Я ничего не изменила — проверьте домашний компьютер и подключение.',status:'error',turnId,trace:frameBuildTestTrace(null,null,Math.round(performance.now()-started),'request_failed')});else toast('Не получилось отправить сообщение — попробуйте ещё раз')}
  finally{frameThinking=false;aiAnalyzing=false;if(btn){btn.disabled=false;btn.textContent='↑'}frameRefreshChat()}
}

async function frameAcquireWakeLock(){if(!('wakeLock' in navigator)||document.visibilityState!=='visible'||frameVoiceWakeLock)return frameVoiceWakeLock;if(frameWakeAcquirePromise)return frameWakeAcquirePromise;frameWakeAcquirePromise=(async()=>{try{const lock=await navigator.wakeLock.request('screen');if(document.visibilityState!=='visible'||(!frameVoiceWanted&&!frameComposerWakeWanted)){try{await lock.release()}catch(e){}return null}frameVoiceWakeLock=lock;lock.addEventListener('release',()=>{if(frameVoiceWakeLock===lock)frameVoiceWakeLock=null});return lock}catch(e){return null}finally{frameWakeAcquirePromise=null}})();return frameWakeAcquirePromise}
async function frameReleaseWakeLock(){try{if(frameWakeAcquirePromise)await frameWakeAcquirePromise;if(document.visibilityState==='visible'&&(frameVoiceWanted||frameComposerWakeWanted))return frameVoiceWakeLock;const lock=frameVoiceWakeLock;frameVoiceWakeLock=null;await lock?.release()}catch(e){}finally{if(document.visibilityState!=='visible'||(!frameVoiceWanted&&!frameComposerWakeWanted))frameVoiceWakeLock=null}}
function frameRefreshWakeLock(){if(frameVoiceWanted||frameComposerWakeWanted)frameAcquireWakeLock();else frameReleaseWakeLock()}
function frameComposerWake(active){clearTimeout(frameComposerWakeTimer);frameComposerWakeTimer=null;if(active){frameComposerWakeWanted=true;frameRefreshWakeLock();return}frameComposerWakeTimer=setTimeout(()=>{const input=$('aiCommandInput');frameComposerWakeWanted=!!(input&&document.activeElement===input);frameRefreshWakeLock()},250)}
function frameVoiceButton(active){const b=$('aiMicBtn'),panel=$('frameVoicePanel'),field=document.querySelector('.frameComposerField');if(b){b.classList.toggle('recording',!!active);b.textContent=active?'■':'🎙️';b.setAttribute('aria-label',active?'Остановить диктовку':'Начать диктовку')}if(panel)panel.hidden=!active;field?.classList.toggle('voiceActive',!!active);clearInterval(frameVoiceUiTimer);frameVoiceUiTimer=null;if(active){frameVoiceStartedAt=Date.now();const tick=()=>{const elapsed=Math.max(0,Math.floor((Date.now()-frameVoiceStartedAt)/1000)),timer=$('frameVoiceTimer');if(timer)timer.textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`};tick();frameVoiceUiTimer=setInterval(tick,250)}}
function frameVoiceText(){return [frameVoiceBase,frameVoiceFinal,frameVoiceInterim].filter(Boolean).join(' ').replace(/\s+/g,' ').trim()}
function frameStartRecognition(){
  const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){frameVoiceWanted=false;frameVoiceButton(false);frameRefreshWakeLock();toast('Распознавание речи недоступно');return}if(!frameVoiceWanted||frameVoiceStopping||document.visibilityState!=='visible')return;
  const session=frameVoiceSession,rec=new SR();aiRecognition=rec;rec.lang='ru-RU';rec.interimResults=true;rec.continuous=true;let committed='';
  rec.onresult=e=>{if(session!==frameVoiceSession||(!frameVoiceWanted&&!frameVoiceStopping))return;let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const text=(e.results[i][0]?.transcript||'').trim();if(e.results[i].isFinal&&text)committed+=(committed?' ':'')+text;else if(text)interim+=(interim?' ':'')+text}frameVoiceInterim=[committed,interim].filter(Boolean).join(' ').trim()};
  rec.onerror=e=>{if(session!==frameVoiceSession)return;const code=String(e?.error||'');if(!frameVoiceStopping&&['not-allowed','service-not-allowed','audio-capture'].includes(code)){frameVoiceWanted=false;frameVoiceButton(false);frameRefreshWakeLock();toast(code==='not-allowed'?'Разрешите микрофон для FRAME':'Микрофон недоступен')}};
  rec.onend=()=>{if(session!==frameVoiceSession)return;if(aiRecognition===rec)aiRecognition=null;if(frameVoiceInterim){frameVoiceFinal=[frameVoiceFinal,frameVoiceInterim].filter(Boolean).join(' ').trim();frameVoiceInterim=''}if(frameVoiceStopping){frameVoiceEndWaiter?.(session,rec);return}if(frameVoiceWanted&&document.visibilityState==='visible'){clearTimeout(frameVoiceRestartTimer);frameVoiceRestartTimer=setTimeout(frameStartRecognition,220)}else frameVoiceButton(false)};
  try{rec.start();frameVoiceButton(true)}catch(e){if(session!==frameVoiceSession)return;aiRecognition=null;if(frameVoiceWanted&&!frameVoiceStopping)frameVoiceRestartTimer=setTimeout(frameStartRecognition,350)}
}
async function frameStopVoice(keepText=true,silent=false){
  if(frameVoiceStopPromise)return frameVoiceStopPromise;
  const session=frameVoiceSession,old=aiRecognition,initial=frameVoiceText();frameVoiceWanted=false;frameVoiceStopping=true;clearTimeout(frameVoiceRestartTimer);frameVoiceRestartTimer=null;
  if(keepText&&initial){frameComposerDraftSession=initial;frameSetComposerText(initial)}frameVoiceButton(false);frameRefreshWakeLock();
  const operation=(async()=>{
    await new Promise(resolve=>{let settled=false,timer=null;const finish=()=>{if(settled)return;settled=true;clearTimeout(timer);if(frameVoiceEndWaiter===waiter)frameVoiceEndWaiter=null;resolve()},waiter=(endedSession,endedRecognition)=>{if(endedSession===session&&endedRecognition===old)finish()};frameVoiceEndWaiter=waiter;timer=setTimeout(finish,450);queueMicrotask(()=>{if(!old){finish();return}try{if(typeof old.stop==='function')old.stop();else{old.abort?.();finish()}}catch(e){try{old.abort?.()}catch(_){}finish()}})});
    if(aiRecognition===old){try{old?.abort?.()}catch(e){}aiRecognition=null}const text=frameVoiceText();if(keepText&&text){frameComposerDraftSession=text;frameSetComposerText(text)}else if(!keepText){frameComposerDraftSession='';const input=$('aiCommandInput');if(input)input.value=''}frameVoiceBase='';frameVoiceFinal='';frameVoiceInterim='';if(session===frameVoiceSession)frameVoiceSession++;frameVoiceStopping=false;frameVoiceButton(false);frameRefreshWakeLock();if(!silent&&keepText&&text)toast('Готово — проверьте текст и отправляйте');return text
  })();
  frameVoiceStopPromise=operation;try{return await operation}finally{if(frameVoiceStopPromise===operation)frameVoiceStopPromise=null}
}
function frameLeaveAi(){clearTimeout(frameComposerWakeTimer);frameComposerWakeTimer=null;frameComposerWakeWanted=false;const input=$('aiCommandInput');if(input)frameComposerDraftSession=input.value;if(frameVoiceWanted||aiRecognition||frameVoiceStopping)void frameStopVoice(true,true);frameReleaseWakeLock()}
startAiVoice=async function(){if(frameVoiceWanted||aiRecognition||frameVoiceStopping){await frameStopVoice(true);return}if(frameVoiceStopPromise)await frameVoiceStopPromise;frameVoiceSession++;const input=$('aiCommandInput');frameVoiceBase=input?.value?.trim()||frameComposerDraftSession.trim();frameVoiceFinal='';frameVoiceInterim='';frameVoiceWanted=true;await frameAcquireWakeLock();frameStartRecognition()}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='visible'){if(frameVoiceWanted){try{aiRecognition?.stop()}catch(e){}}frameReleaseWakeLock()}else{frameRefreshWakeLock();if(frameVoiceWanted&&!aiRecognition)frameStartRecognition()}});

bindAiResult=function(){frameBindChatActions()};bindAiView=function(){frameRestorePending();if($('aiAnalyzeBtn'))$('aiAnalyzeBtn').onclick=analyzeAiInput;if($('aiMicBtn'))$('aiMicBtn').onclick=startAiVoice;if($('frameAttachBtn'))$('frameAttachBtn').onclick=frameShowAttachMenu;if($('frameTestBtn'))$('frameTestBtn').onclick=frameShowTestTranscript;const input=$('aiCommandInput');if(input){if(frameComposerDraftSession)frameSetComposerText(frameComposerDraftSession);input.addEventListener('focus',()=>frameComposerWake(true));input.addEventListener('blur',()=>frameComposerWake(false));input.addEventListener('input',()=>{frameComposerDraftSession=input.value;frameAutoGrowInput();frameComposerWake(document.activeElement===input)});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();analyzeAiInput()}})}frameBindChatActions();frameScrollChat();frameRenderConnectionDot();frameUpdateTestButton();if(aiServerUrl()&&!aiBrainStatus)checkAiBrain({toastResult:false});else frameOwnerFlush()};
const frameCoreApplyAiDraft=applyAiDraft;applyAiDraft=async function(authorizationToken=''){const d=frameRestorePending()||aiDraft,id=d?.chatId||'',policyError=frameDraftPolicyError(d);if(policyError){if(id)frameUpdateChat(id,{status:'error',text:policyError,draft:null,links:[]});if(d)aiRevokeDraftAuthorization(d);frameClearPendingIf(id);toast(policyError);if(route==='ai')render();return false}if(d)aiDraft=d;const applied=await frameCoreApplyAiDraft(authorizationToken),receipt=frameLastApplyReceipt||{ok:false,error:'Не удалось подтвердить запись',links:[]};if(id&&applied===true&&receipt.ok&&receipt.postconditionVerified){if(receipt.targetKey)frameSetTopic(receipt.targetKey);frameUpdateChat(id,{status:'applied',text:frameAppliedSummary(d,receipt),draft:null,links:receipt.links||[],receipt},{eventType:'action.apply_result',receipt});frameClearPendingIf(id);if(route==='ai')render()}else if(id&&authorizationToken){frameUpdateChat(id,{status:'error',text:`Не получилось записать изменение: ${receipt.error||'сохранение не подтверждено'}. Ничего не отмечаю как готовое.`,draft:null,links:[],receipt},{eventType:'action.apply_result',receipt});frameClearPendingIf(id);if(route==='ai')render()}return applied===true&&receipt.ok===true&&receipt.postconditionVerified===true};
console.info('[FRAME] 2.8.0 chat-first companion loaded');
