'use strict';

// FRAME 2.7.6 AI Chat.
const FRAME_CHAT_KEY='frameAiChatV270';
const FRAME_CHAT_PENDING_KEY='frameAiPendingV270';
const FRAME_CHAT_TOPIC_KEY='frameAiTopicV270';
const FRAME_CHAT_LIMIT=100;
let frameVoiceWanted=false,frameComposerWakeWanted=false,frameVoiceRestartTimer=null,frameComposerWakeTimer=null,frameVoiceBase='',frameVoiceWakeLock=null,frameWakeAcquirePromise=null,frameVoiceSession=0,frameThinking=false,frameApplyingDraftId='';
const frameSessionMessageIds=new Set();
let frameChatSession=[],framePendingSession=null,frameTopicSession='';

function frameRetireLegacyAiChatStorage(){for(const key of [FRAME_CHAT_KEY,FRAME_CHAT_PENDING_KEY,FRAME_CHAT_TOPIC_KEY]){try{if(typeof storageRemove==='function')storageRemove(key);else localStorage.removeItem(key)}catch(e){}}}
frameRetireLegacyAiChatStorage();
function frameChatMessages(){return frameChatSession.slice()}
function frameProviderChatMessages(){return frameChatMessages().filter(x=>frameSessionMessageIds.has(String(x?.id||'')))}
function frameSaveChat(items){frameChatSession=(items||[]).slice(-FRAME_CHAT_LIMIT)}
function frameAddChat(message){const items=frameChatMessages(),item={id:uid(),at:now(),role:'assistant',status:'done',...message};frameSessionMessageIds.add(String(item.id));items.push(item);frameSaveChat(items);return item}
function frameUpdateChat(id,patch){const items=frameChatMessages(),i=items.findIndex(x=>x.id===id);if(i<0)return null;items[i]={...items[i],...patch};frameSaveChat(items);return items[i]}
function frameSavePending(draft){framePendingSession=draft||null}
function frameDraftPolicyError(d){try{const error=typeof aiFieldSafeDraftError==='function'?String(aiFieldSafeDraftError(d)||''):'';if(error)return error;if(aiEffectiveMode(d?.mode)==='field_safe'&&Array.isArray(d.actions)&&d.actions.length&&!String(d.targetLabel||'').trim())return 'FRAME заблокировал старый план без зафиксированной цели. Ничего не применено.';return ''}catch(e){return 'FRAME не смог проверить безопасность плана. Ничего не применено.'}}
function frameRestorePending(){if(aiDraft?.ok){if(!frameDraftPolicyError(aiDraft))return aiDraft;aiDraft=null;frameClearPending()}const d=framePendingSession;if(d?.ok){if(frameDraftPolicyError(d)){frameClearPending();return null}aiDraft=d;return d}return null}
function frameClearPending(){framePendingSession=null}
function frameChatTime(v){try{return new Date(v).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}catch(e){return ''}}
function frameTopic(){return frameTopicSession}
function frameSetTopic(key=''){if(key&&aiTargetByKey(key)){frameTopicSession=key;routeState.aiTarget=key}}
const FRAME_TARGET_GENERIC=new Set(['монтаж','работа','работы','работам','готова','готов','поставь','поставить','процент','процентов']);
function frameWorkTargetScore(order,text=''){const tokens=aiTokens(text).filter(x=>x.length>=4&&!FRAME_TARGET_GENERIC.has(x));let best=0;for(const row of order?.works||[]){const name=aiNorm(row.name),nameTokens=aiTokens(name);let score=0;for(const token of tokens){if(name.includes(token))score+=3;else if(nameTokens.some(x=>x.startsWith(token)||token.startsWith(x)))score+=2}best=Math.max(best,score)}return best}
function frameDetectTarget(text=''){const norm=aiNorm(text),tokens=aiTokens(norm),addingWork=/(?:добавь|добавить|допработ|новая\\s+работа)/.test(norm);let best='',bestScore=0,tied=false;for(const x of aiAllTargets()){const hay=aiNorm(`${x.object.contact.address} ${x.object.contact.name} ${x.order.title}`);let score=0;for(const token of tokens){if(token.length>=4&&hay.includes(token))score+=2}for(const p of aiNorm(x.object.contact.address).split(' ')){const s=aiStem(p);if(s.length>=5&&norm.includes(s))score+=4}if(!addingWork)score+=frameWorkTargetScore(x.order,norm);if(score>bestScore){bestScore=score;best=x.key;tied=false}else if(score===bestScore&&score>0&&best!==x.key)tied=true}return bestScore>=3&&!tied?best:''}
function frameTopicLabel(){const t=aiTargetByKey(frameTopic());return t?(t.object.contact.address||t.order.title||''):''}
function frameTargetLabel(key=''){const t=aiTargetByKey(String(key||''));if(!t)return '';return [t.object?.contact?.address,t.order?.title].map(x=>String(x||'').trim()).filter(Boolean).join(' · ')}
function frameAttachTargetSnapshot(d){if(d?.ok&&aiEffectiveMode(d.mode)==='field_safe'&&Array.isArray(d.actions)&&d.actions.length)d.targetLabel=frameTargetLabel(d.targetKey);return d}
function framePlanHtml(d){if(!d?.actions?.length)return '';const target=aiEffectiveMode(d.mode)==='field_safe'&&d.targetLabel?`<div class="frameChatPlanRow frameChatPlanTarget"><span>Объект: <strong>${esc(d.targetLabel)}</strong></span></div>`:'';return `<div class="frameChatPlan">${target}${d.actions.map(a=>`<div class="frameChatPlanRow"><span>${esc(aiBrainActionSummary(a))}</span></div>`).join('')}</div>`}
function framePendingControls(m){return `<div class="frameChatActions"><button class="btn primary" data-chat-apply="${esc(m.id)}">Применить</button><button class="btn ghost" data-chat-cancel="${esc(m.id)}">Отмена</button></div>`}
function frameThinkingHtml(){return frameThinking?`<article class="frameChatMessage fromFrame frameThinking"><div class="frameChatBubble"><div class="frameThinkingRow"><span>FRAME думает</span><i></i><i></i><i></i></div></div></article>`:''}
function frameChatHtml(){const items=frameChatMessages();const body=!items.length?`<div class="frameChatWelcome"><span class="frameChatOrb">✦</span><div><strong>FRAME</strong><p>Скажите, что произошло. Я сама найду объект и продолжу разговор в его контексте.</p></div></div>`:items.map(m=>{const p=m.role==='assistant'&&m.status==='pending'&&m.draft,s=m.status==='applied'?'✓ Применено':m.status==='cancelled'?'Отменено':'';return `<article class="frameChatMessage ${m.role==='user'?'fromUser':'fromFrame'} ${p?'hasPlan':''}"><div class="frameChatBubble"><small class="frameChatTime">${esc(frameChatTime(m.at))}</small><div class="frameChatText">${esc(m.text||'')}</div>${p?framePlanHtml(m.draft):''}${p?framePendingControls(m):''}${s?`<div class="frameChatStatus ${m.status}">${s}${m.status==='applied'?` <button type="button" data-chat-undo>Отменить</button>`:''}</div>`:''}</div></article>`}).join('');return body+frameThinkingHtml()}
function frameScrollChat(){requestAnimationFrame(()=>{const x=$('frameChatFeed');if(x)x.scrollTop=x.scrollHeight})}
function frameRefreshChat(){const f=$('frameChatFeed');if(f)f.innerHTML=frameChatHtml();frameBindChatActions();frameScrollChat()}
function frameCancelPending(id=''){const d=frameRestorePending();if(d)aiRevokeDraftAuthorization(d);if(id)frameUpdateChat(id,{status:'cancelled',draft:null});else if(d?.chatId)frameUpdateChat(d.chatId,{status:'cancelled',draft:null});aiDraft=null;frameClearPending();frameRefreshChat()}
function frameBindChatActions(){$$('[data-chat-apply]').forEach(b=>{const d=frameRestorePending();if(!d||d.chatId!==b.dataset.chatApply||!aiBindDisplayedDraftApply(b,d,async authorization=>{if(frameApplyingDraftId)return toast('FRAME уже применяет этот план');frameApplyingDraftId=d.chatId;b.disabled=true;$$('[data-chat-cancel]').forEach(x=>x.disabled=true);try{aiDraft=d;await applyAiDraft(authorization)}finally{frameApplyingDraftId=''}})){b.disabled=true;b.title='Этот план уже не активен'}});$$('[data-chat-cancel]').forEach(b=>b.onclick=()=>frameCancelPending(b.dataset.chatCancel));$$('[data-chat-undo]').forEach(b=>b.onclick=undoLastAiAction)}

const frameCoreContextPayload=aiContextPayload;
aiContextPayload=function(){const topic=frameTopic();if(topic)routeState.aiTarget=topic;const base=frameCoreContextPayload();const conversation=frameProviderChatMessages().slice(-24).map(m=>({role:m.role==='user'?'user':'assistant',content:String(m.text||''),status:m.status||'done'}));return {...base,current_target:topic||'',conversation_target:frameTopicLabel(),conversation,conversation_rules:['The conversation_target is locked until the user explicitly names another object.','Pronouns like this object, here, these works and considering the above always refer to conversation_target.','Recent user facts in conversation are newer than stored progress until actions are applied.','Never switch to another object/order merely because it exists in context.']}}

checkAiBrain=async function({toastResult=true}={}){const base=aiServerUrl(),token=aiServerToken(),current=()=>base===aiServerUrl()&&token===aiServerToken();if(!base){aiRecordAuthenticatedHealth('',{url:base,authenticated:false});aiBrainStatus={ok:false,message:'Адрес не задан'};return aiBrainStatus}try{const d=await aiBrainFetch('/health',{method:'GET'},{base,token});if(!current())return aiBrainStatus||{ok:false,message:'Настройки AI Brain изменились'};const healthMode=String(d.mode||d.detail?.mode||''),fieldVerified=aiRecordAuthenticatedHealth(healthMode,{url:base,authenticated:!!token&&!!d.ok}),ok=!!d.ok&&(!aiConfiguredFieldSafe(base)||fieldVerified);aiBrainStatus={ok,provider:d.provider||'',model:d.model||'',mode:healthMode,detail:d.detail||{},message:ok?'Готов к работе':aiConfiguredFieldSafe(base)?'Безопасный режим сервера не подтверждён':'AI Brain пока не готов'};if(toastResult)toast(ok?'FRAME на связи':aiBrainStatus.message);return aiBrainStatus}catch(e){if(!current())return aiBrainStatus||{ok:false,message:'Настройки AI Brain изменились'};aiRecordAuthenticatedHealth('',{url:base,authenticated:false});aiBrainStatus={ok:false,message:String(e?.message||e)};if(toastResult)toast('FRAME не может связаться с AI Brain');return aiBrainStatus}finally{if(route==='ai')requestAnimationFrame(frameRenderConnectionDot)}};
function frameRenderConnectionDot(){const d=$('frameConnectionDot');if(d)d.className=`frameConnectionDot ${aiBrainStatus?.ok?'ok':aiBrainStatus?'bad':'wait'}`}
renderAiView=function(){frameRestorePending();const mic=!!(window.SpeechRecognition||window.webkitSpeechRecognition);return `<section class="frameChatView"><header class="frameChatTop"><button class="frameChatBack" type="button" data-go="dashboard" aria-label="Назад">‹</button><div class="frameChatTitle">FRAME <i id="frameConnectionDot" class="frameConnectionDot ${aiBrainStatus?.ok?'ok':aiBrainStatus?'bad':'wait'}"></i></div></header><main id="frameChatFeed" class="frameChatFeed">${frameChatHtml()}</main><footer class="frameChatComposer"><button id="frameAttachBtn" class="frameComposerIcon" type="button">＋</button><textarea id="aiCommandInput" rows="1" placeholder="Сообщение FRAME"></textarea><button id="aiMicBtn" class="frameComposerIcon mic" type="button" ${mic?'':'disabled'}>🎙️</button><button id="aiAnalyzeBtn" class="frameSendBtn" type="button">↑</button></footer></section>`}
function frameAutoGrowInput(){const i=$('aiCommandInput');if(i){i.style.height='auto';i.style.height=Math.min(132,i.scrollHeight)+'px'}}
function frameShowAttachMenu(){openSheet(`<div class="sectionTitle"><div><h1>Добавить</h1><p class="help compact">Фото, чек и файлы подключим здесь.</p></div><button class="sheetCloseIcon" data-close-sheet>×</button></div>`)}

function frameHardClearComposer(){frameVoiceBase='';const i=$('aiCommandInput');if(i){i.value='';i.style.height='auto'}}
analyzeAiInput=async function(){const input=$('aiCommandInput'),text=String(input?.value||'').trim();if(!text)return toast('Сначала скажите или напишите сообщение');frameStopVoice(false);frameVoiceSession++;frameHardClearComposer();const detected=frameDetectTarget(text);if(detected)frameSetTopic(detected);else if(frameTopic())routeState.aiTarget=frameTopic();const old=frameRestorePending();if(old?.chatId){aiRevokeDraftAuthorization(old);frameUpdateChat(old.chatId,{status:'cancelled',draft:null})}aiDraft=null;frameClearPending();frameAddChat({role:'user',text,status:'done'});frameThinking=true;frameRefreshChat();aiAnalyzing=true;const btn=$('aiAnalyzeBtn');if(btn){btn.disabled=true;btn.textContent='…'}try{let draft;if(aiServerUrl()){const response=await requestAiBrain(text);draft=brainDraftFromResponse(text,response)}else draft=parseAiCommand(text,frameTopic()||routeState.aiTarget);if(draft?.targetKey&&aiTargetByKey(draft.targetKey)){const explicit=frameDetectTarget(text);if(explicit)frameSetTopic(explicit);else if(frameTopic())draft.targetKey=frameTopic()}frameAttachTargetSnapshot(draft);const policyError=frameDraftPolicyError(draft);if(policyError)draft={ok:false,source:'brain',blocked:true,error:policyError,text};if(draft?.ok&&draft.type==='read_answer')frameAddChat({role:'assistant',text:draft.summary,status:'done'});else if(draft?.ok){const m=frameAddChat({role:'assistant',text:draft.summary||'Проверьте изменение.',status:'pending',draft});draft.chatId=m.id;m.draft.chatId=m.id;frameUpdateChat(m.id,{draft:m.draft});aiDraft=draft;frameSavePending(draft)}else frameAddChat({role:'assistant',text:draft?.error||'Нужно уточнение.',status:'done'})}catch(e){console.error(e);frameAddChat({role:'assistant',text:'Не удалось связаться с AI Brain. Проверьте компьютер и туннель.',status:'done'})}finally{frameThinking=false;aiAnalyzing=false;frameHardClearComposer();if(btn){btn.disabled=false;btn.textContent='↑'}frameRefreshChat()}}

async function frameAcquireWakeLock(){if(!('wakeLock' in navigator)||document.visibilityState!=='visible'||frameVoiceWakeLock)return frameVoiceWakeLock;if(frameWakeAcquirePromise)return frameWakeAcquirePromise;frameWakeAcquirePromise=(async()=>{try{const lock=await navigator.wakeLock.request('screen');if(document.visibilityState!=='visible'||(!frameVoiceWanted&&!frameComposerWakeWanted)){try{await lock.release()}catch(e){}return null}frameVoiceWakeLock=lock;lock.addEventListener('release',()=>{if(frameVoiceWakeLock===lock)frameVoiceWakeLock=null});return lock}catch(e){return null}finally{frameWakeAcquirePromise=null}})();return frameWakeAcquirePromise}
async function frameReleaseWakeLock(){try{if(frameWakeAcquirePromise)await frameWakeAcquirePromise;if(document.visibilityState==='visible'&&(frameVoiceWanted||frameComposerWakeWanted))return frameVoiceWakeLock;const lock=frameVoiceWakeLock;frameVoiceWakeLock=null;await lock?.release()}catch(e){}finally{if(document.visibilityState!=='visible'||(!frameVoiceWanted&&!frameComposerWakeWanted))frameVoiceWakeLock=null}}
function frameRefreshWakeLock(){if(frameVoiceWanted||frameComposerWakeWanted)frameAcquireWakeLock();else frameReleaseWakeLock()}
function frameComposerWake(active){clearTimeout(frameComposerWakeTimer);frameComposerWakeTimer=null;if(active){frameComposerWakeWanted=true;frameRefreshWakeLock();return}frameComposerWakeTimer=setTimeout(()=>{const input=$('aiCommandInput');frameComposerWakeWanted=!!(input&&document.activeElement===input);frameRefreshWakeLock()},250)}
function frameVoiceButton(active){const b=$('aiMicBtn');if(!b)return;b.classList.toggle('recording',!!active);b.textContent=active?'■':'🎙️'}
function frameStartRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){frameVoiceWanted=false;frameVoiceButton(false);frameRefreshWakeLock();toast('Распознавание речи недоступно');return}if(!frameVoiceWanted||document.visibilityState!=='visible')return;const session=frameVoiceSession;const rec=new SR();aiRecognition=rec;rec.lang='ru-RU';rec.interimResults=true;rec.continuous=true;let committed='';rec.onresult=e=>{if(session!==frameVoiceSession||!frameVoiceWanted)return;let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=(e.results[i][0]?.transcript||'').trim();if(e.results[i].isFinal&&t)committed+=(committed?' ':'')+t;else if(t)interim+=(interim?' ':'')+t}const input=$('aiCommandInput');if(input){input.value=[frameVoiceBase,committed,interim].filter(Boolean).join(' ').trim();frameAutoGrowInput()}};rec.onerror=e=>{if(session!==frameVoiceSession)return;const code=String(e?.error||'');if(['not-allowed','service-not-allowed','audio-capture'].includes(code)){frameVoiceWanted=false;frameVoiceButton(false);frameRefreshWakeLock();toast(code==='not-allowed'?'Разрешите микрофон для FRAME':'Микрофон недоступен')}};rec.onend=()=>{if(session!==frameVoiceSession)return;aiRecognition=null;const i=$('aiCommandInput');if(i&&frameVoiceWanted)frameVoiceBase=i.value.trim();if(frameVoiceWanted&&document.visibilityState==='visible'){clearTimeout(frameVoiceRestartTimer);frameVoiceRestartTimer=setTimeout(frameStartRecognition,220)}else frameVoiceButton(false)};try{rec.start();frameVoiceButton(true)}catch(e){if(session!==frameVoiceSession)return;aiRecognition=null;frameVoiceRestartTimer=setTimeout(frameStartRecognition,350)}}
function frameStopVoice(keepText=true){frameVoiceWanted=false;frameVoiceSession++;clearTimeout(frameVoiceRestartTimer);frameVoiceRestartTimer=null;const old=aiRecognition;aiRecognition=null;try{old?.abort?.()}catch(e){try{old?.stop()}catch(_){}}if(!keepText)frameVoiceBase='';frameVoiceButton(false);frameRefreshWakeLock()}
function frameLeaveAi(){clearTimeout(frameComposerWakeTimer);frameComposerWakeTimer=null;frameComposerWakeWanted=false;frameStopVoice(true);frameReleaseWakeLock()}
startAiVoice=async function(){if(frameVoiceWanted){frameStopVoice(true);return}frameVoiceSession++;const input=$('aiCommandInput');frameVoiceBase=input?.value?.trim()||'';frameVoiceWanted=true;await frameAcquireWakeLock();frameStartRecognition()}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='visible'){if(frameVoiceWanted){try{aiRecognition?.stop()}catch(e){}}frameReleaseWakeLock()}else{frameRefreshWakeLock();if(frameVoiceWanted&&!aiRecognition)frameStartRecognition()}});

bindAiResult=function(){frameBindChatActions()};bindAiView=function(){frameRestorePending();if($('aiAnalyzeBtn'))$('aiAnalyzeBtn').onclick=analyzeAiInput;if($('aiMicBtn'))$('aiMicBtn').onclick=startAiVoice;if($('frameAttachBtn'))$('frameAttachBtn').onclick=frameShowAttachMenu;const input=$('aiCommandInput');if(input){input.addEventListener('focus',()=>frameComposerWake(true));input.addEventListener('blur',()=>frameComposerWake(false));input.addEventListener('input',()=>{frameAutoGrowInput();frameComposerWake(document.activeElement===input)});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();analyzeAiInput()}})}frameHardClearComposer();frameBindChatActions();frameScrollChat();frameRenderConnectionDot();if(aiServerUrl()&&!aiBrainStatus)checkAiBrain({toastResult:false})};
const frameCoreApplyAiDraft=applyAiDraft;applyAiDraft=async function(authorizationToken=''){const d=frameRestorePending()||aiDraft,id=d?.chatId||'',policyError=frameDraftPolicyError(d);if(policyError){if(id)frameUpdateChat(id,{status:'cancelled',text:policyError,draft:null});if(d)aiRevokeDraftAuthorization(d);aiDraft=null;frameClearPending();toast(policyError);if(route==='ai')render();return false}if(d)aiDraft=d;const applied=await frameCoreApplyAiDraft(authorizationToken);if(id&&applied===true){frameUpdateChat(id,{status:'applied',draft:null});frameClearPending();if(route==='ai')render()}else if(id&&authorizationToken){frameUpdateChat(id,{status:'cancelled',draft:null});frameClearPending();aiDraft=null;if(route==='ai')render()}return applied===true};
console.info('[FRAME] 2.7.6 AI Chat loaded');
